import type { ScenarioEntry } from "../types.js";

/**
 * Real-world scenarios (§15).
 *
 * Each becomes an interactive role-play with the AI tutor: `tutorRole`,
 * `setting` and `goal` are injected straight into the tutor's system prompt, so
 * the tutor stays in character and the learner has something concrete to
 * accomplish rather than an open-ended chat.
 */
export const SCENARIOS: ScenarioEntry[] = [
  {
    slug: "restaurant",
    title: "At a restaurant",
    levelCode: "A1",
    setting: "A busy tapas bar in Madrid at 2pm",
    goal: "Get a table, order food and drink, and ask for the bill",
    tutorRole: "a friendly but brisk waiter who is busy and speaks at a natural pace",
    icon: "UtensilsCrossed",
    usefulPhrases: [
      "Una mesa para dos, por favor.",
      "¿Qué me recomienda?",
      "Para mí, …",
      "¿Tiene algo sin carne?",
      "La cuenta, por favor.",
    ],
  },
  {
    slug: "airport",
    title: "At an airport",
    levelCode: "A2",
    setting: "The check-in desk and security at Barajas airport",
    goal: "Check in, deal with a luggage problem, and find your gate",
    tutorRole: "an airline check-in agent, polite and procedural",
    icon: "Plane",
    usefulPhrases: [
      "Tengo una reserva a nombre de…",
      "¿Puedo llevar esto en cabina?",
      "¿Dónde está la puerta de embarque?",
      "Mi maleta no ha llegado.",
    ],
  },
  {
    slug: "hotel",
    title: "At a hotel",
    levelCode: "A2",
    setting: "The reception desk of a small hotel in Valencia",
    goal: "Check in, ask about breakfast and wifi, and report a problem with the room",
    tutorRole: "a hotel receptionist, helpful and formal, using usted",
    icon: "BedDouble",
    usefulPhrases: [
      "Tengo una habitación reservada.",
      "¿A qué hora es el desayuno?",
      "¿Cuál es la contraseña del wifi?",
      "El aire acondicionado no funciona.",
    ],
  },
  {
    slug: "shopping",
    title: "Going shopping",
    levelCode: "A2",
    setting: "A clothes shop in a shopping centre",
    goal: "Find your size, try something on, and pay",
    tutorRole: "a shop assistant who is attentive and asks questions",
    icon: "ShoppingBag",
    usefulPhrases: [
      "¿Tiene esto en la talla M?",
      "¿Me lo puedo probar?",
      "Me queda un poco grande.",
      "¿Puedo pagar con tarjeta?",
    ],
  },
  {
    slug: "doctor",
    title: "Calling a doctor",
    levelCode: "A2",
    setting: "A phone call to a health centre",
    goal: "Make an appointment and describe your symptoms",
    tutorRole: "a receptionist at a health centre, then the doctor",
    icon: "Stethoscope",
    usefulPhrases: [
      "Quería pedir cita.",
      "Me duele…",
      "Tengo fiebre desde hace dos días.",
      "¿Es urgente?",
    ],
  },
  {
    slug: "meeting-people",
    title: "Meeting someone new",
    levelCode: "A1",
    setting: "A friend's birthday party where you know nobody",
    goal: "Introduce yourself and keep a conversation going for five turns",
    tutorRole: "another guest at the party, curious and chatty",
    icon: "Users",
    usefulPhrases: [
      "¿Cómo te llamas?",
      "¿De dónde eres?",
      "¿A qué te dedicas?",
      "¿Y tú, de qué conoces a…?",
    ],
  },
  {
    slug: "renting-apartment",
    title: "Renting an apartment",
    levelCode: "B1",
    setting: "A flat viewing with the landlord",
    goal: "Ask about the rent, bills and contract, and negotiate",
    tutorRole: "a landlord who is friendly but evasive about the details",
    icon: "Key",
    usefulPhrases: [
      "¿Cuánto es el alquiler al mes?",
      "¿Están incluidos los gastos?",
      "¿Cuánto hay que dejar de fianza?",
      "¿El contrato es de un año?",
    ],
  },
  {
    slug: "university",
    title: "At university",
    levelCode: "B1",
    setting: "The administration office and a seminar room",
    goal: "Enrol in a course and take part in a seminar discussion",
    tutorRole: "an administrator, then a fellow student in a seminar",
    icon: "GraduationCap",
    usefulPhrases: [
      "Quería matricularme en…",
      "¿Cuándo es la fecha límite?",
      "No estoy del todo de acuerdo con…",
      "¿Podrías repetir eso?",
    ],
  },
  {
    slug: "job-interview",
    title: "A job interview",
    levelCode: "B2",
    setting: "A formal interview at a Spanish company",
    goal: "Present your experience, answer difficult questions, and ask your own",
    tutorRole: "an interviewer who probes and follows up on vague answers",
    icon: "Briefcase",
    usefulPhrases: [
      "Llevo cinco años trabajando en…",
      "Mi mayor fortaleza es…",
      "Me interesa este puesto porque…",
      "¿Cómo es el equipo?",
    ],
  },
  {
    slug: "business-meeting",
    title: "A business meeting",
    levelCode: "B2",
    setting: "A project meeting with Spanish colleagues",
    goal: "Present a proposal, handle objections, and agree next steps",
    tutorRole: "a colleague who disagrees with your proposal but is professional",
    icon: "Presentation",
    usefulPhrases: [
      "Propongo que…",
      "Entiendo tu punto, sin embargo…",
      "¿Qué plazos manejamos?",
      "Quedamos entonces en que…",
    ],
  },
  {
    slug: "debate",
    title: "A debate",
    levelCode: "C1",
    setting: "A structured debate on a current issue",
    goal: "Defend a position, concede fairly, and rebut with evidence",
    tutorRole: "a well-informed opponent who argues the opposite side rigorously",
    icon: "Scale",
    usefulPhrases: [
      "Desde mi punto de vista…",
      "Es cierto que… no obstante…",
      "Habría que matizar que…",
      "Los datos no respaldan esa afirmación.",
    ],
  },
  {
    slug: "friends",
    title: "Talking with friends",
    levelCode: "B1",
    setting: "A bar with friends on a Friday night",
    goal: "Keep up with fast, colloquial conversation and tell a story",
    tutorRole: "a close friend using slang, irony and interruptions",
    icon: "Beer",
    usefulPhrases: ["¿Qué tal todo?", "No me digas.", "Total, que…", "Venga, cuéntame."],
  },
];
