import type { Row } from "./row.js";

export const A1_ROWS: Row[] = [
  // Greetings & courtesy
  ["hola", "hello", "OH-la", "phrase", null, "greetings", "¡Hola! ¿Qué tal?", "Hi! How's it going?", { synonyms: ["buenas"] }],
  ["adiós", "goodbye", "ah-DYOS", "phrase", null, "greetings", "Adiós, hasta mañana.", "Goodbye, see you tomorrow.", { antonyms: ["hola"] }],
  ["buenos días", "good morning", "BWE-nos DEE-as", "phrase", null, "greetings", "Buenos días, señora López.", "Good morning, Mrs. López."],
  ["buenas tardes", "good afternoon", "BWE-nas TAR-des", "phrase", null, "greetings", "Buenas tardes, ¿en qué puedo ayudarle?", "Good afternoon, how can I help you?"],
  ["buenas noches", "good evening / good night", "BWE-nas NO-ches", "phrase", null, "greetings", "Buenas noches, que descanses.", "Good night, sleep well."],
  ["por favor", "please", "por fa-BOR", "phrase", null, "courtesy", "Un café, por favor.", "A coffee, please."],
  ["gracias", "thank you", "GRA-thyas", "phrase", null, "courtesy", "Muchas gracias por tu ayuda.", "Thank you very much for your help."],
  ["de nada", "you're welcome", "de NA-da", "phrase", null, "courtesy", "—Gracias. —De nada.", "—Thanks. —You're welcome."],
  ["perdón", "sorry / excuse me", "per-DON", "phrase", null, "courtesy", "Perdón, ¿puedo pasar?", "Excuse me, may I get past?", { synonyms: ["lo siento", "disculpe"] }],
  ["sí", "yes", "see", "adverb", null, "basics", "Sí, claro.", "Yes, of course.", { antonyms: ["no"] }],
  ["no", "no / not", "no", "adverb", null, "basics", "No, gracias.", "No, thank you.", { antonyms: ["sí"] }],

  // Core verbs — the ones everything else is built on
  ["ser", "to be (permanent)", "ser", "verb", null, "verbs", "Soy profesora.", "I am a teacher.", { related: ["estar"], difficulty: 2 }],
  ["estar", "to be (state/location)", "es-TAR", "verb", null, "verbs", "Estoy en casa.", "I am at home.", { related: ["ser"], difficulty: 2 }],
  ["tener", "to have", "te-NER", "verb", null, "verbs", "Tengo dos hermanos.", "I have two brothers.", { difficulty: 2 }],
  ["hacer", "to do / to make", "a-THER", "verb", null, "verbs", "¿Qué haces?", "What are you doing?", { difficulty: 2 }],
  ["ir", "to go", "eer", "verb", null, "verbs", "Voy al trabajo.", "I'm going to work.", { antonyms: ["venir"], difficulty: 2 }],
  ["querer", "to want / to love", "ke-RER", "verb", null, "verbs", "Quiero un vaso de agua.", "I want a glass of water."],
  ["poder", "to be able to / can", "po-DER", "verb", null, "verbs", "¿Puedes ayudarme?", "Can you help me?"],
  ["hablar", "to speak", "a-BLAR", "verb", null, "verbs", "Hablo un poco de español.", "I speak a little Spanish."],
  ["comer", "to eat", "ko-MER", "verb", null, "verbs", "Comemos a las dos.", "We eat at two."],
  ["vivir", "to live", "bee-BEER", "verb", null, "verbs", "Vivo en Madrid.", "I live in Madrid."],
  ["saber", "to know (facts)", "sa-BER", "verb", null, "verbs", "No sé la respuesta.", "I don't know the answer.", { related: ["conocer"] }],
  ["conocer", "to know (people/places)", "ko-no-THER", "verb", null, "verbs", "Conozco a su hermana.", "I know his sister.", { related: ["saber"] }],
  ["necesitar", "to need", "ne-the-see-TAR", "verb", null, "verbs", "Necesito ayuda.", "I need help."],
  ["gustar", "to be pleasing (to like)", "goos-TAR", "verb", null, "verbs", "Me gusta el café.", "I like coffee.", { difficulty: 3 }],
  ["trabajar", "to work", "tra-ba-HAR", "verb", null, "verbs", "Trabajo en una oficina.", "I work in an office."],
  ["estudiar", "to study", "es-too-DYAR", "verb", null, "verbs", "Estudio español.", "I study Spanish."],
  ["beber", "to drink", "be-BER", "verb", null, "verbs", "Bebo agua.", "I drink water.", { synonyms: ["tomar"] }],

  // People & family
  ["la familia", "family", "la fa-MEE-lya", "noun", "f", "family", "Mi familia es grande.", "My family is big."],
  ["la madre", "mother", "la MA-dre", "noun", "f", "family", "Mi madre se llama Ana.", "My mother's name is Ana.", { synonyms: ["mamá"], antonyms: ["padre"] }],
  ["el padre", "father", "el PA-dre", "noun", "m", "family", "Mi padre trabaja mucho.", "My father works a lot.", { synonyms: ["papá"], antonyms: ["madre"] }],
  ["el hermano", "brother", "el er-MA-no", "noun", "m", "family", "Tengo un hermano mayor.", "I have an older brother."],
  ["la hermana", "sister", "la er-MA-na", "noun", "f", "family", "Mi hermana estudia medicina.", "My sister studies medicine."],
  ["el hijo", "son", "el EE-ho", "noun", "m", "family", "Su hijo tiene cinco años.", "Her son is five."],
  ["la hija", "daughter", "la EE-ha", "noun", "f", "family", "Mi hija va al colegio.", "My daughter goes to school."],
  ["el amigo", "friend (male)", "el a-MEE-go", "noun", "m", "people", "Es mi mejor amigo.", "He's my best friend."],
  ["la amiga", "friend (female)", "la a-MEE-ga", "noun", "f", "people", "Voy con una amiga.", "I'm going with a friend."],
  ["el hombre", "man", "el OM-bre", "noun", "m", "people", "El hombre de la tienda es amable.", "The man in the shop is kind.", { antonyms: ["mujer"] }],
  ["la mujer", "woman / wife", "la moo-HER", "noun", "f", "people", "Esa mujer es mi jefa.", "That woman is my boss.", { antonyms: ["hombre"] }],
  ["el niño", "child / boy", "el NEE-nyo", "noun", "m", "people", "El niño juega en el parque.", "The boy plays in the park."],
  ["el nombre", "name", "el NOM-bre", "noun", "m", "basics", "¿Cuál es tu nombre?", "What's your name?"],

  // Numbers
  ["uno", "one", "OO-no", "number", null, "numbers", "Solo tengo uno.", "I only have one."],
  ["dos", "two", "dos", "number", null, "numbers", "Dos cafés, por favor.", "Two coffees, please.", { pluralForm: null }],
  ["tres", "three", "tres", "number", null, "numbers", "Son las tres.", "It's three o'clock.", { pluralForm: null }],
  ["cuatro", "four", "KWA-tro", "number", null, "numbers", "Tengo cuatro clases hoy.", "I have four classes today."],
  ["cinco", "five", "THEEN-ko", "number", null, "numbers", "Cinco euros.", "Five euros."],
  ["seis", "six", "seys", "number", null, "numbers", "Seis personas.", "Six people.", { pluralForm: null }],
  ["siete", "seven", "SYE-te", "number", null, "numbers", "Siete días.", "Seven days."],
  ["ocho", "eight", "O-cho", "number", null, "numbers", "Ocho horas de trabajo.", "Eight hours of work."],
  ["nueve", "nine", "NWE-be", "number", null, "numbers", "Nueve de la mañana.", "Nine in the morning."],
  ["diez", "ten", "dyeth", "number", null, "numbers", "Diez minutos.", "Ten minutes."],
  ["veinte", "twenty", "BEYN-te", "number", null, "numbers", "Tengo veinte años.", "I'm twenty years old."],
  ["cien", "one hundred", "thyen", "number", null, "numbers", "Cien euros.", "One hundred euros."],

  // Food & drink
  ["la comida", "food / meal", "la ko-MEE-da", "noun", "f", "food", "La comida está lista.", "The food is ready."],
  ["el agua", "water", "el A-gwa", "noun", "f", "food", "Un vaso de agua, por favor.", "A glass of water, please.", { pluralForm: "las aguas", difficulty: 3 }],
  ["el café", "coffee", "el ka-FE", "noun", "m", "food", "Tomo café con leche.", "I have coffee with milk.", { pluralForm: "los cafés" }],
  ["el pan", "bread", "el pan", "noun", "m", "food", "Compro pan cada mañana.", "I buy bread every morning."],
  ["la leche", "milk", "la LE-che", "noun", "f", "food", "No me gusta la leche fría.", "I don't like cold milk."],
  ["el vino", "wine", "el BEE-no", "noun", "m", "food", "Un vino tinto, por favor.", "A red wine, please."],
  ["la cerveza", "beer", "la ther-BE-tha", "noun", "f", "food", "Dos cervezas, por favor.", "Two beers, please."],
  ["la carne", "meat", "la KAR-ne", "noun", "f", "food", "No como carne.", "I don't eat meat."],
  ["el pescado", "fish (as food)", "el pes-KA-do", "noun", "m", "food", "El pescado está muy fresco.", "The fish is very fresh."],
  ["la fruta", "fruit", "la FROO-ta", "noun", "f", "food", "Como fruta todos los días.", "I eat fruit every day."],
  ["el restaurante", "restaurant", "el res-tow-RAN-te", "noun", "m", "food", "Vamos a un restaurante.", "Let's go to a restaurant."],
  ["la cuenta", "the bill", "la KWEN-ta", "noun", "f", "food", "La cuenta, por favor.", "The bill, please."],

  // Time & days
  ["el día", "day", "el DEE-a", "noun", "m", "time", "Todos los días estudio.", "I study every day.", { pluralForm: "los días" }],
  ["la semana", "week", "la se-MA-na", "noun", "f", "time", "La semana que viene.", "Next week."],
  ["el año", "year", "el A-nyo", "noun", "m", "time", "Este año aprendo español.", "This year I'm learning Spanish."],
  ["la hora", "hour / time", "la O-ra", "noun", "f", "time", "¿Qué hora es?", "What time is it?"],
  ["hoy", "today", "oy", "adverb", null, "time", "Hoy no trabajo.", "I'm not working today."],
  ["mañana", "tomorrow / morning", "ma-NYA-na", "adverb", null, "time", "Mañana voy a Madrid.", "Tomorrow I'm going to Madrid.", { antonyms: ["ayer"] }],
  ["ayer", "yesterday", "a-YER", "adverb", null, "time", "Ayer fue lunes.", "Yesterday was Monday.", { antonyms: ["mañana"] }],
  ["ahora", "now", "a-O-ra", "adverb", null, "time", "Ahora no puedo.", "I can't right now."],
  ["siempre", "always", "SYEM-pre", "adverb", null, "time", "Siempre llego tarde.", "I'm always late.", { antonyms: ["nunca"] }],
  ["nunca", "never", "NOON-ka", "adverb", null, "time", "Nunca he estado allí.", "I've never been there.", { antonyms: ["siempre"] }],
  ["el lunes", "Monday", "el LOO-nes", "noun", "m", "time", "El lunes empiezo el curso.", "On Monday I start the course.", { pluralForm: "los lunes" }],

  // Places & everyday objects
  ["la casa", "house / home", "la KA-sa", "noun", "f", "places", "Estoy en casa.", "I'm at home."],
  ["la ciudad", "city", "la thyoo-DAD", "noun", "f", "places", "Madrid es una ciudad grande.", "Madrid is a big city."],
  ["la calle", "street", "la KA-ye", "noun", "f", "places", "Vivo en esta calle.", "I live on this street."],
  ["el trabajo", "work / job", "el tra-BA-ho", "noun", "m", "work", "Voy al trabajo en metro.", "I go to work by metro."],
  ["la tienda", "shop", "la TYEN-da", "noun", "f", "shopping", "La tienda abre a las nueve.", "The shop opens at nine."],
  ["el dinero", "money", "el dee-NE-ro", "noun", "m", "shopping", "No tengo dinero.", "I don't have any money."],
  ["el coche", "car", "el KO-che", "noun", "m", "travel", "Voy en coche.", "I'm going by car.", { region: "es-ES", regionalVariant: "el carro", synonyms: ["el carro", "el auto"] }],
  ["el carro", "car (Latin America)", "el KA-rro", "noun", "m", "travel", "Mi carro está en el taller.", "My car is at the garage.", { region: "es-419", regionalVariant: "el coche", synonyms: ["el coche"] }],
  ["el libro", "book", "el LEE-bro", "noun", "m", "objects", "Leo un libro cada mes.", "I read a book every month."],
  ["el teléfono", "telephone", "el te-LE-fo-no", "noun", "m", "objects", "Mi teléfono no funciona.", "My phone isn't working."],

  // High-frequency adjectives & function words
  ["bueno", "good", "BWE-no", "adjective", null, "adjectives", "Es un buen restaurante.", "It's a good restaurant.", { antonyms: ["malo"] }],
  ["malo", "bad", "MA-lo", "adjective", null, "adjectives", "Hace mal tiempo.", "The weather is bad.", { antonyms: ["bueno"] }],
  ["grande", "big", "GRAN-de", "adjective", null, "adjectives", "Una casa grande.", "A big house.", { antonyms: ["pequeño"] }],
  ["pequeño", "small", "pe-KE-nyo", "adjective", null, "adjectives", "Un piso pequeño.", "A small flat.", { antonyms: ["grande"] }],
  ["nuevo", "new", "NWE-bo", "adjective", null, "adjectives", "Tengo un trabajo nuevo.", "I have a new job.", { antonyms: ["viejo"] }],
  ["mucho", "much / a lot", "MOO-cho", "adjective", null, "quantity", "Trabajo mucho.", "I work a lot.", { antonyms: ["poco"] }],
  ["poco", "little / few", "PO-ko", "adjective", null, "quantity", "Hablo un poco de español.", "I speak a little Spanish.", { antonyms: ["mucho"] }],
  ["muy", "very", "mwee", "adverb", null, "quantity", "Estoy muy cansado.", "I'm very tired."],
  ["también", "also / too", "tam-BYEN", "adverb", null, "basics", "Yo también.", "Me too.", { antonyms: ["tampoco"] }],
  ["pero", "but", "PE-ro", "conjunction", null, "connectors", "Quiero ir, pero no puedo.", "I want to go, but I can't."],
  ["porque", "because", "POR-ke", "conjunction", null, "connectors", "No voy porque estoy enfermo.", "I'm not going because I'm ill."],
  ["cansado", "tired", "kan-SA-do", "adjective", null, "feelings", "Estoy muy cansado hoy.", "I'm very tired today."],
  ["contento", "happy / pleased", "kon-TEN-to", "adjective", null, "feelings", "Estoy contenta con el resultado.", "I'm pleased with the result.", { synonyms: ["feliz"], antonyms: ["triste"] }],
  ["barato", "cheap", "ba-RA-to", "adjective", null, "shopping", "Es más barato en el mercado.", "It's cheaper at the market.", { antonyms: ["caro"] }],
  ["caro", "expensive", "KA-ro", "adjective", null, "shopping", "Este móvil es muy caro.", "This phone is very expensive.", { antonyms: ["barato"] }],
  // Concrete everyday nouns — high-frequency and easy to picture, which is what
  // makes them the right words to attach memory hooks to.
  ["el perro", "dog", "el PE-rro", "noun", "m", "animals", "Mi perro se llama Toby.", "My dog is called Toby."],
  ["el gato", "cat", "el GA-to", "noun", "m", "animals", "El gato duerme en el sofá.", "The cat sleeps on the sofa."],
  ["el caballo", "horse", "el ka-BA-yo", "noun", "m", "animals", "Monta a caballo los domingos.", "He rides a horse on Sundays."],
  ["la mesa", "table", "la ME-sa", "noun", "f", "objects", "La mesa es de madera.", "The table is made of wood."],
  ["la silla", "chair", "la SEE-ya", "noun", "f", "objects", "Siéntate en esta silla.", "Sit on this chair."],
  ["la llave", "key", "la YA-be", "noun", "f", "objects", "He perdido las llaves.", "I have lost my keys."],
  ["el reloj", "watch / clock", "el re-LOH", "noun", "m", "objects", "Mi reloj está roto.", "My watch is broken.", { pluralForm: "los relojes" }],
  ["el zapato", "shoe", "el tha-PA-to", "noun", "m", "clothing", "Estos zapatos son muy cómodos.", "These shoes are very comfortable."],
  ["el queso", "cheese", "el KE-so", "noun", "m", "food", "Me gusta el queso manchego.", "I like manchego cheese."],
  ["la mano", "hand", "la MA-no", "noun", "f", "body", "Dame la mano.", "Give me your hand.", { difficulty: 2 }],
  ["el problema", "problem", "el pro-BLE-ma", "noun", "m", "abstract", "No hay ningún problema.", "There is no problem at all.", { difficulty: 2 }],
  // ─── Colours ──────────────────────────────────────────────────────────────
  ["rojo", "red", "RO-ho", "adjective", null, "colours", "Tengo un coche rojo.", "I have a red car."],
  ["azul", "blue", "a-THOOL", "adjective", null, "colours", "El cielo está azul hoy.", "The sky is blue today.", { pluralForm: "azules" }],
  ["verde", "green", "BER-de", "adjective", null, "colours", "Me gusta el té verde.", "I like green tea."],
  ["amarillo", "yellow", "a-ma-REE-yo", "adjective", null, "colours", "El sol es amarillo.", "The sun is yellow."],
  ["negro", "black", "NE-gro", "adjective", null, "colours", "Lleva un abrigo negro.", "She is wearing a black coat."],
  ["blanco", "white", "BLAN-ko", "adjective", null, "colours", "Quiero una camisa blanca.", "I want a white shirt."],
  ["gris", "grey", "grees", "adjective", null, "colours", "Hoy el día está gris.", "It is a grey day today.", { pluralForm: "grises" }],
  ["marrón", "brown", "ma-RRON", "adjective", null, "colours", "Tiene los ojos marrones.", "He has brown eyes.", { pluralForm: "marrones" }],
  ["el color", "colour", "el ko-LOR", "noun", "m", "colours", "¿Cuál es tu color favorito?", "What is your favourite colour?"],

  // ─── The body ─────────────────────────────────────────────────────────────
  ["el ojo", "eye", "el O-ho", "noun", "m", "body", "Me duele el ojo derecho.", "My right eye hurts."],
  ["la boca", "mouth", "la BO-ka", "noun", "f", "body", "Abre la boca, por favor.", "Open your mouth, please."],
  ["la nariz", "nose", "la na-REETH", "noun", "f", "body", "Tengo la nariz tapada.", "My nose is blocked."],
  ["el brazo", "arm", "el BRA-tho", "noun", "m", "body", "Me rompí el brazo.", "I broke my arm."],
  ["la pierna", "leg", "la PYER-na", "noun", "f", "body", "Me duelen las piernas.", "My legs hurt."],
  ["el pie", "foot", "el pye", "noun", "m", "body", "Vamos a pie.", "Let us go on foot."],
  ["el pelo", "hair", "el PE-lo", "noun", "m", "body", "Tiene el pelo largo.", "She has long hair."],
  ["el corazón", "heart", "el ko-ra-THON", "noun", "m", "body", "El corazón late rápido.", "The heart beats fast."],
  ["el estómago", "stomach", "el es-TO-ma-go", "noun", "m", "body", "Me duele el estómago.", "My stomach hurts."],

  // ─── Clothing ─────────────────────────────────────────────────────────────
  ["la camisa", "shirt", "la ka-MEE-sa", "noun", "f", "clothing", "Esta camisa es muy bonita.", "This shirt is very nice."],
  ["el pantalón", "trousers", "el pan-ta-LON", "noun", "m", "clothing", "Necesito un pantalón negro.", "I need black trousers."],
  ["el vestido", "dress", "el bes-TEE-do", "noun", "m", "clothing", "Lleva un vestido azul.", "She is wearing a blue dress."],
  ["el abrigo", "coat", "el a-BREE-go", "noun", "m", "clothing", "Hace frío, coge el abrigo.", "It is cold, take your coat."],
  ["la falda", "skirt", "la FAL-da", "noun", "f", "clothing", "La falda me queda bien.", "The skirt fits me well."],
  ["el sombrero", "hat", "el som-BRE-ro", "noun", "m", "clothing", "Lleva un sombrero grande.", "He wears a big hat."],

  // ─── Weather & nature ─────────────────────────────────────────────────────
  ["el tiempo", "weather / time", "el TYEM-po", "noun", "m", "weather", "¿Qué tiempo hace hoy?", "What is the weather like today?"],
  ["el sol", "sun", "el sol", "noun", "m", "weather", "Hoy hace sol.", "It is sunny today."],
  ["la lluvia", "rain", "la YOO-bya", "noun", "f", "weather", "La lluvia no para.", "The rain does not stop."],
  ["el frío", "cold", "el FREE-o", "noun", "m", "weather", "Tengo mucho frío.", "I am very cold."],
  ["el calor", "heat", "el ka-LOR", "noun", "m", "weather", "En agosto hace mucho calor.", "It is very hot in August."],
  ["la nieve", "snow", "la NYE-be", "noun", "f", "weather", "La nieve cubre la montaña.", "The snow covers the mountain."],
  ["el viento", "wind", "el BYEN-to", "noun", "m", "weather", "Hace mucho viento.", "It is very windy."],
  ["el mar", "sea", "el mar", "noun", "m", "nature", "Vamos al mar en verano.", "We go to the sea in summer."],
  ["la montaña", "mountain", "la mon-TA-nya", "noun", "f", "nature", "Subimos a la montaña.", "We climbed the mountain."],
  ["el árbol", "tree", "el AR-bol", "noun", "m", "nature", "Hay un árbol en el jardín.", "There is a tree in the garden.", { pluralForm: "los árboles" }],
  ["la flor", "flower", "la flor", "noun", "f", "nature", "Le regalé una flor.", "I gave her a flower.", { pluralForm: "las flores" }],

  // ─── Months & time ────────────────────────────────────────────────────────
  ["enero", "January", "e-NE-ro", "noun", "m", "time", "Mi cumpleaños es en enero.", "My birthday is in January."],
  ["julio", "July", "HOO-lyo", "noun", "m", "time", "En julio vamos de vacaciones.", "In July we go on holiday."],
  ["el mes", "month", "el mes", "noun", "m", "time", "Este mes tengo mucho trabajo.", "I have a lot of work this month.", { pluralForm: "los meses" }],
  ["el minuto", "minute", "el mee-NOO-to", "noun", "m", "time", "Espera un minuto.", "Wait a minute."],
  ["la noche", "night", "la NO-che", "noun", "f", "time", "Trabajo por la noche.", "I work at night."],
  ["la tarde", "afternoon / evening", "la TAR-de", "noun", "f", "time", "Nos vemos por la tarde.", "See you in the afternoon."],
  ["temprano", "early", "tem-PRA-no", "adverb", null, "time", "Me levanto temprano.", "I get up early.", { antonyms: ["tarde"] }],
  ["tarde", "late", "TAR-de", "adverb", null, "time", "Llegué tarde a la reunión.", "I arrived late to the meeting.", { antonyms: ["temprano"] }],
  ["antes", "before", "AN-tes", "adverb", null, "time", "Antes vivía en Madrid.", "I used to live in Madrid before.", { antonyms: ["después"] }],
  ["después", "after / afterwards", "des-PWES", "adverb", null, "time", "Después vamos al cine.", "Afterwards we are going to the cinema.", { antonyms: ["antes"] }],

  // ─── Numbers ──────────────────────────────────────────────────────────────
  ["once", "eleven", "ON-the", "number", null, "numbers", "Son las once de la mañana.", "It is eleven in the morning."],
  ["quince", "fifteen", "KEEN-the", "number", null, "numbers", "Tengo quince euros.", "I have fifteen euros."],
  ["treinta", "thirty", "TREYN-ta", "number", null, "numbers", "Mi hermano tiene treinta años.", "My brother is thirty."],
  ["cincuenta", "fifty", "theen-KWEN-ta", "number", null, "numbers", "Cuesta cincuenta euros.", "It costs fifty euros."],
  ["mil", "thousand", "meel", "number", null, "numbers", "El billete cuesta mil pesos.", "The ticket costs a thousand pesos."],
  ["primero", "first", "pree-ME-ro", "adjective", null, "numbers", "Es el primero de la lista.", "He is the first on the list."],
  ["último", "last", "OOL-tee-mo", "adjective", null, "numbers", "Es el último día.", "It is the last day."],

  // ─── Home ─────────────────────────────────────────────────────────────────
  ["la puerta", "door", "la PWER-ta", "noun", "f", "home", "Cierra la puerta, por favor.", "Close the door, please."],
  ["la ventana", "window", "la ben-TA-na", "noun", "f", "home", "Abre la ventana.", "Open the window."],
  ["la cama", "bed", "la KA-ma", "noun", "f", "home", "Voy a la cama temprano.", "I go to bed early."],
  ["la cocina", "kitchen", "la ko-THEE-na", "noun", "f", "home", "Estoy en la cocina.", "I am in the kitchen."],
  ["el baño", "bathroom", "el BA-nyo", "noun", "m", "home", "¿Dónde está el baño?", "Where is the bathroom?"],
  ["el piso", "flat / floor", "el PEE-so", "noun", "m", "home", "Vivo en un piso pequeño.", "I live in a small flat.", { region: "es-ES", regionalVariant: "el departamento" }],
  ["el jardín", "garden", "el har-DEEN", "noun", "m", "home", "Los niños juegan en el jardín.", "The children play in the garden.", { pluralForm: "los jardines" }],

  // ─── High-frequency verbs ─────────────────────────────────────────────────
  ["ver", "to see", "ber", "verb", null, "verbs", "No veo nada.", "I cannot see anything."],
  ["dar", "to give", "dar", "verb", null, "verbs", "Dame el libro, por favor.", "Give me the book, please."],
  ["venir", "to come", "be-NEER", "verb", null, "verbs", "¿Vienes conmigo?", "Are you coming with me?", { antonyms: ["ir"] }],
  ["decir", "to say / to tell", "de-THEER", "verb", null, "verbs", "¿Qué dices?", "What are you saying?"],
  ["poner", "to put", "po-NER", "verb", null, "verbs", "Pon el plato en la mesa.", "Put the plate on the table."],
  ["salir", "to go out / to leave", "sa-LEER", "verb", null, "verbs", "Salgo de casa a las ocho.", "I leave home at eight.", { antonyms: ["entrar"] }],
  ["entrar", "to go in / to enter", "en-TRAR", "verb", null, "verbs", "Entra, por favor.", "Come in, please.", { antonyms: ["salir"] }],
  ["llegar", "to arrive", "ye-GAR", "verb", null, "verbs", "El tren llega a las nueve.", "The train arrives at nine."],
  ["pasar", "to pass / to happen", "pa-SAR", "verb", null, "verbs", "¿Qué pasa?", "What is happening?"],
  ["llevar", "to carry / to wear", "ye-BAR", "verb", null, "verbs", "Llevo una chaqueta azul.", "I am wearing a blue jacket."],
  ["dejar", "to leave / to let", "de-HAR", "verb", null, "verbs", "Deja las llaves en la mesa.", "Leave the keys on the table."],
  ["empezar", "to begin", "em-pe-THAR", "verb", null, "verbs", "La clase empieza a las diez.", "The class begins at ten.", { antonyms: ["terminar"], synonyms: ["comenzar"] }],
  ["terminar", "to finish", "ter-mee-NAR", "verb", null, "verbs", "Termino el trabajo a las seis.", "I finish work at six.", { antonyms: ["empezar"] }],
  ["comprar", "to buy", "kom-PRAR", "verb", null, "verbs", "Voy a comprar pan.", "I am going to buy bread.", { antonyms: ["vender"] }],
  ["vender", "to sell", "ben-DER", "verb", null, "verbs", "Venden fruta en el mercado.", "They sell fruit at the market.", { antonyms: ["comprar"] }],
  ["abrir", "to open", "a-BREER", "verb", null, "verbs", "¿A qué hora abren?", "What time do they open?", { antonyms: ["cerrar"] }],
  ["cerrar", "to close", "the-RRAR", "verb", null, "verbs", "Cierran a las nueve.", "They close at nine.", { antonyms: ["abrir"] }],
  ["leer", "to read", "le-ER", "verb", null, "verbs", "Leo el periódico cada mañana.", "I read the paper every morning."],
  ["escribir", "to write", "es-kree-BEER", "verb", null, "verbs", "Escribo un correo a mi jefa.", "I am writing an email to my boss."],
  ["escuchar", "to listen", "es-koo-CHAR", "verb", null, "verbs", "Escucho música en el tren.", "I listen to music on the train."],
  ["mirar", "to look at / to watch", "mee-RAR", "verb", null, "verbs", "Mira ese edificio.", "Look at that building."],
  ["esperar", "to wait / to hope", "es-pe-RAR", "verb", null, "verbs", "Espera aquí un momento.", "Wait here a moment."],
  ["buscar", "to look for", "boos-KAR", "verb", null, "verbs", "Busco mis llaves.", "I am looking for my keys.", { antonyms: ["encontrar"] }],
  ["encontrar", "to find", "en-kon-TRAR", "verb", null, "verbs", "No encuentro el móvil.", "I cannot find my phone.", { antonyms: ["buscar"] }],
  ["ayudar", "to help", "a-yoo-DAR", "verb", null, "verbs", "¿Me puedes ayudar?", "Can you help me?"],
  ["aprender", "to learn", "a-pren-DER", "verb", null, "verbs", "Aprendo español.", "I am learning Spanish.", { synonyms: ["estudiar"] }],
  ["enseñar", "to teach / to show", "en-se-NYAR", "verb", null, "verbs", "Ella enseña matemáticas.", "She teaches mathematics."],
  ["jugar", "to play", "hoo-GAR", "verb", null, "verbs", "Los niños juegan en el parque.", "The children play in the park."],
  ["dormir", "to sleep", "dor-MEER", "verb", null, "verbs", "Duermo ocho horas.", "I sleep eight hours."],
  ["andar", "to walk", "an-DAR", "verb", null, "verbs", "Ando al trabajo cada día.", "I walk to work every day.", { synonyms: ["caminar"] }],
  ["correr", "to run", "ko-RRER", "verb", null, "verbs", "Corro por el parque.", "I run in the park."],
  ["viajar", "to travel", "bya-HAR", "verb", null, "verbs", "Me gusta viajar en tren.", "I like travelling by train."],
  ["pagar", "to pay", "pa-GAR", "verb", null, "verbs", "Quiero pagar con tarjeta.", "I want to pay by card."],
  ["cocinar", "to cook", "ko-thee-NAR", "verb", null, "verbs", "Mi padre cocina muy bien.", "My father cooks very well."],
  ["llamar", "to call", "ya-MAR", "verb", null, "verbs", "Te llamo esta noche.", "I will call you tonight."],
  ["pensar", "to think", "pen-SAR", "verb", null, "verbs", "Pienso que tienes razón.", "I think you are right."],
  ["creer", "to believe", "kre-ER", "verb", null, "verbs", "Creo que va a llover.", "I think it is going to rain."],
  ["sentir", "to feel", "sen-TEER", "verb", null, "verbs", "Lo siento mucho.", "I am very sorry."],

  // ─── Places & transport ───────────────────────────────────────────────────
  ["la escuela", "school", "la es-KWE-la", "noun", "f", "places", "Los niños van a la escuela.", "The children go to school.", { synonyms: ["el colegio"] }],
  ["el hospital", "hospital", "el os-pee-TAL", "noun", "m", "places", "Trabaja en el hospital.", "She works at the hospital."],
  ["el mercado", "market", "el mer-KA-do", "noun", "m", "places", "Compro fruta en el mercado.", "I buy fruit at the market."],
  ["el parque", "park", "el PAR-ke", "noun", "m", "places", "Paseamos por el parque.", "We walk through the park."],
  ["la playa", "beach", "la PLA-ya", "noun", "f", "places", "Vamos a la playa el domingo.", "We are going to the beach on Sunday."],
  ["el centro", "centre / downtown", "el THEN-tro", "noun", "m", "places", "Vivo en el centro.", "I live in the centre."],
  ["el tren", "train", "el tren", "noun", "m", "travel", "El tren sale a las ocho.", "The train leaves at eight.", { pluralForm: "los trenes" }],
  ["el autobús", "bus", "el ow-to-BOOS", "noun", "m", "travel", "Voy en autobús.", "I go by bus.", { pluralForm: "los autobuses" }],
  ["el avión", "plane", "el a-BYON", "noun", "m", "travel", "El avión llega tarde.", "The plane is arriving late.", { pluralForm: "los aviones" }],

  // ─── Everyday nouns ───────────────────────────────────────────────────────
  ["la cosa", "thing", "la KO-sa", "noun", "f", "objects", "Tengo muchas cosas que hacer.", "I have a lot of things to do."],
  ["la vez", "time / occasion", "la beth", "noun", "f", "abstract", "Otra vez, por favor.", "Again, please.", { pluralForm: "las veces" }],
  ["la vida", "life", "la BEE-da", "noun", "f", "abstract", "Así es la vida.", "That is life."],
  ["la parte", "part", "la PAR-te", "noun", "f", "abstract", "Esta parte es difícil.", "This part is difficult."],
  ["la gente", "people", "la HEN-te", "noun", "f", "people", "Hay mucha gente aquí.", "There are a lot of people here."],
  ["el país", "country", "el pa-EES", "noun", "m", "places", "Es un país muy grande.", "It is a very big country.", { pluralForm: "los países" }],
  ["la carta", "letter", "la KAR-ta", "noun", "f", "objects", "Escribí una carta a mi abuela.", "I wrote a letter to my grandmother."],
  ["el papel", "paper / role", "el pa-PEL", "noun", "m", "objects", "Necesito un papel para escribir.", "I need a piece of paper to write on.", { pluralForm: "los papeles" }],
  ["la palabra", "word", "la pa-LA-bra", "noun", "f", "language", "No entiendo esa palabra.", "I do not understand that word."],

  // ─── Everyday adjectives & adverbs ────────────────────────────────────────
  ["fácil", "easy", "FA-theel", "adjective", null, "adjectives", "El examen fue fácil.", "The exam was easy.", { antonyms: ["difícil"], pluralForm: "fáciles" }],
  ["difícil", "difficult", "dee-FEE-theel", "adjective", null, "adjectives", "Es una pregunta difícil.", "It is a difficult question.", { antonyms: ["fácil"], pluralForm: "difíciles" }],
  ["largo", "long", "LAR-go", "adjective", null, "adjectives", "Fue un viaje largo.", "It was a long journey.", { antonyms: ["corto"] }],
  ["corto", "short", "KOR-to", "adjective", null, "adjectives", "Es un vídeo corto.", "It is a short video.", { antonyms: ["largo"] }],
  ["alto", "tall / high", "AL-to", "adjective", null, "adjectives", "Mi hermano es muy alto.", "My brother is very tall.", { antonyms: ["bajo"] }],
  ["bajo", "short / low", "BA-ho", "adjective", null, "adjectives", "El precio es bajo.", "The price is low.", { antonyms: ["alto"] }],
  ["viejo", "old", "BYE-ho", "adjective", null, "adjectives", "Es un edificio viejo.", "It is an old building.", { antonyms: ["nuevo", "joven"] }],
  ["joven", "young", "HO-ben", "adjective", null, "adjectives", "Es muy joven todavía.", "He is still very young.", { antonyms: ["viejo"], pluralForm: "jóvenes" }],
  ["bonito", "pretty / nice", "bo-NEE-to", "adjective", null, "adjectives", "Qué casa tan bonita.", "What a pretty house.", { antonyms: ["feo"] }],
  ["feo", "ugly", "FE-o", "adjective", null, "adjectives", "El tiempo está feo hoy.", "The weather is ugly today.", { antonyms: ["bonito"] }],
  ["limpio", "clean", "LEEM-pyo", "adjective", null, "adjectives", "La cocina está limpia.", "The kitchen is clean.", { antonyms: ["sucio"] }],
  ["sucio", "dirty", "SOO-thyo", "adjective", null, "adjectives", "El coche está muy sucio.", "The car is very dirty.", { antonyms: ["limpio"] }],
  ["rápido", "fast", "RA-pee-do", "adjective", null, "adjectives", "Es un tren rápido.", "It is a fast train.", { antonyms: ["lento"] }],
  ["lento", "slow", "LEN-to", "adjective", null, "adjectives", "El servicio es muy lento.", "The service is very slow.", { antonyms: ["rápido"] }],
  ["fuerte", "strong", "FWER-te", "adjective", null, "adjectives", "El café está muy fuerte.", "The coffee is very strong.", { antonyms: ["débil"] }],
  ["importante", "important", "eem-por-TAN-te", "adjective", null, "adjectives", "Es una reunión importante.", "It is an important meeting."],
  ["listo", "ready / clever", "LEES-to", "adjective", null, "adjectives", "¿Estás listo?", "Are you ready?"],
  ["ocupado", "busy", "o-koo-PA-do", "adjective", null, "adjectives", "Hoy estoy muy ocupado.", "I am very busy today."],
  ["libre", "free / available", "LEE-bre", "adjective", null, "adjectives", "¿Estás libre el viernes?", "Are you free on Friday?"],
  ["bastante", "quite / enough", "bas-TAN-te", "adverb", null, "quantity", "Es bastante caro.", "It is quite expensive."],
  ["demasiado", "too much", "de-ma-SYA-do", "adverb", null, "quantity", "Hay demasiado ruido.", "There is too much noise."],
  ["casi", "almost", "KA-see", "adverb", null, "quantity", "Casi termino.", "I have almost finished."],
  ["todavía", "still / yet", "to-da-BEE-a", "adverb", null, "time", "Todavía no he comido.", "I have not eaten yet.", { synonyms: ["aún"] }],
  ["ya", "already / now", "ya", "adverb", null, "time", "Ya está listo.", "It is ready now."],
  ["aquí", "here", "a-KEE", "adverb", null, "places", "Ven aquí, por favor.", "Come here, please.", { antonyms: ["allí"] }],
  ["allí", "there", "a-YEE", "adverb", null, "places", "El banco está allí.", "The bank is over there.", { antonyms: ["aquí"] }],
  ["cerca", "near", "THER-ka", "adverb", null, "places", "El metro está cerca.", "The metro is nearby.", { antonyms: ["lejos"] }],
  ["lejos", "far", "LE-hos", "adverb", null, "places", "Mi casa está lejos.", "My house is far away.", { antonyms: ["cerca"] }],
  ["juntos", "together", "HOON-tos", "adjective", null, "people", "Trabajamos juntos.", "We work together."],
  ["solo", "alone / only", "SO-lo", "adverb", null, "people", "Vivo solo.", "I live alone."],

  // ─── Function words ───────────────────────────────────────────────────────
  ["con", "with", "kon", "preposition", null, "connectors", "Voy con mi hermana.", "I am going with my sister.", { antonyms: ["sin"] }],
  ["sin", "without", "seen", "preposition", null, "connectors", "Un café sin azúcar, por favor.", "A coffee without sugar, please.", { antonyms: ["con"] }],
  ["sobre", "on / about", "SO-bre", "preposition", null, "connectors", "El libro está sobre la mesa.", "The book is on the table."],
  ["entre", "between", "EN-tre", "preposition", null, "connectors", "Está entre el banco y la tienda.", "It is between the bank and the shop."],
  ["hasta", "until / as far as", "AS-ta", "preposition", null, "connectors", "Trabajo hasta las seis.", "I work until six.", { antonyms: ["desde"] }],
  ["desde", "from / since", "DES-de", "preposition", null, "connectors", "Vivo aquí desde marzo.", "I have lived here since March.", { antonyms: ["hasta"] }],
  ["durante", "during", "doo-RAN-te", "preposition", null, "connectors", "Llovió durante la noche.", "It rained during the night."],
  ["si", "if", "see", "conjunction", null, "connectors", "Si llueve, no salgo.", "If it rains, I am not going out."],
  ["cuando", "when", "KWAN-do", "conjunction", null, "connectors", "Cuando llego, te llamo.", "When I arrive, I will call you."],
  ["mientras", "while", "MYEN-tras", "conjunction", null, "connectors", "Escucho música mientras cocino.", "I listen to music while I cook."],
  ["nada", "nothing", "NA-da", "pronoun", null, "basics", "No tengo nada que decir.", "I have nothing to say.", { antonyms: ["todo"] }],
  ["todo", "everything / all", "TO-do", "pronoun", null, "basics", "Todo está bien.", "Everything is fine.", { antonyms: ["nada"] }],
  ["algo", "something", "AL-go", "pronoun", null, "basics", "¿Quieres algo de beber?", "Do you want something to drink?"],
  ["alguien", "someone", "AL-gyen", "pronoun", null, "basics", "Alguien llamó por teléfono.", "Someone called on the phone.", { antonyms: ["nadie"] }],
  ["nadie", "nobody", "NA-dye", "pronoun", null, "basics", "No hay nadie en casa.", "There is nobody at home.", { antonyms: ["alguien"] }],
  ["otro", "other / another", "O-tro", "adjective", null, "basics", "Quiero otro café.", "I want another coffee."],
  ["mismo", "same", "MEES-mo", "adjective", null, "basics", "Vivimos en la misma calle.", "We live on the same street."],
  ["cada", "each / every", "KA-da", "adjective", null, "basics", "Cada día es distinto.", "Each day is different."],

  // ─── Referenced by other entries as synonyms, antonyms and variants ───────
  ["buenas", "hi / hello (informal greeting)", "BWE-nas", "phrase", null, "greetings", "¡Buenas! ¿Qué tal?", "Hi! How are things?", { region: "es-ES" }],
  ["lo siento", "I am sorry", "lo SYEN-to", "phrase", null, "greetings", "Lo siento, llego tarde.", "I am sorry, I am late."],
  ["disculpe", "excuse me (formal)", "dees-KOOL-pe", "phrase", null, "greetings", "Disculpe, ¿tiene un momento?", "Excuse me, do you have a moment?"],
  ["tomar", "to take / to drink", "to-MAR", "verb", null, "verbs", "Tomo café por la mañana.", "I drink coffee in the morning."],
  ["mamá", "mum", "ma-MA", "noun", "f", "family", "Mamá llega el sábado.", "Mum arrives on Saturday."],
  ["papá", "dad", "pa-PA", "noun", "m", "family", "Papá trabaja los fines de semana.", "Dad works at weekends."],
  ["el auto", "car (Latin America)", "el AW-to", "noun", "m", "travel", "El auto está en el taller.", "The car is at the garage.", { region: "es-419", regionalVariant: "el coche" }],
  ["tampoco", "neither / not either", "tam-PO-ko", "adverb", null, "function_words", "Yo tampoco lo sabía.", "I did not know either."],
  ["feliz", "happy", "fe-LEETH", "adjective", null, "feelings", "Estoy feliz por ti.", "I am happy for you.", { pluralForm: "felices" }],
  ["caminar", "to walk", "ka-mee-NAR", "verb", null, "verbs", "Caminamos hasta la plaza.", "We walked to the square.", { synonyms: ["andar"] }],
  ["el colegio", "school", "el ko-LE-hyo", "noun", "m", "education", "Los niños salen del colegio a las cinco.", "The children leave school at five."],
  ["débil", "weak", "DE-beel", "adjective", null, "descriptions", "Se siente débil todavía.", "He still feels weak.", { antonyms: ["fuerte"], pluralForm: "débiles" }],
  ["antipático", "unfriendly", "an-tee-PA-tee-ko", "adjective", null, "people", "El camarero fue muy antipático.", "The waiter was very unfriendly."],
  ["claro", "of course / clear", "KLA-ro", "adverb", null, "expressions", "Claro, ven cuando quieras.", "Of course, come whenever you like."],
  ["la forma", "way / shape", "la FOR-ma", "noun", "f", "abstract", "Hay otra forma de hacerlo.", "There is another way of doing it."],
];
