import type { Row } from "./row.js";

export const A1_ROWS: Row[] = [
  // Greetings & courtesy
  ["hola", "hello", "OH-la", "phrase", null, "greetings", "¡Hola! ¿Qué tal?", "Hi! How's it going?", { synonyms: ["buenas"] }],
  ["adiós", "goodbye", "ah-DYOS", "phrase", null, "greetings", "Adiós, hasta mañana.", "Goodbye, see you tomorrow.", { antonyms: ["hola"] }],
  ["buenos días", "good morning", "BWE-nos DEE-as", "phrase", null, "greetings", "Buenos días, señora López.", "Good morning, Mrs. López."],
  ["buenas tardes", "good afternoon", "BWE-nas TAR-des", "phrase", null, "greetings", "Buenas tardes, ¿en qué puedo ayudarle?", "Good afternoon, how can I help you?"],
  ["buenas noches", "good evening / good night", "BWE-nas NO-ches", "phrase", null, "greetings", "Buenas noches, que descanses.", "Good night, sleep well."],
  ["por favor", "please", "por fa-BOR", "phrase", null, "courtesy", "Un café, por favor.", "A coffee, please."],
  ["gracias", "thank you", "GRA-thyas", "phrase", null, "courtesy", "Muchas gracias por tu ayuda.", "Thank you very much for your help."],
  ["de nada", "you're welcome", "de NA-da", "phrase", null, "courtesy", "—Gracias. —De nada.", "—Thanks. —You're welcome."],
  ["perdón", "sorry / excuse me", "per-DON", "phrase", null, "courtesy", "Perdón, ¿puedo pasar?", "Excuse me, may I get past?", { synonyms: ["lo siento", "disculpe"] }],
  ["sí", "yes", "see", "adverb", null, "basics", "Sí, claro.", "Yes, of course.", { antonyms: ["no"] }],
  ["no", "no / not", "no", "adverb", null, "basics", "No, gracias.", "No, thank you.", { antonyms: ["sí"] }],

  // Core verbs — the ones everything else is built on
  ["ser", "to be (permanent)", "ser", "verb", null, "verbs", "Soy profesora.", "I am a teacher.", { related: ["estar"], difficulty: 2 }],
  ["estar", "to be (state/location)", "es-TAR", "verb", null, "verbs", "Estoy en casa.", "I am at home.", { related: ["ser"], difficulty: 2 }],
  ["tener", "to have", "te-NER", "verb", null, "verbs", "Tengo dos hermanos.", "I have two brothers.", { difficulty: 2 }],
  ["hacer", "to do / to make", "a-THER", "verb", null, "verbs", "¿Qué haces?", "What are you doing?", { difficulty: 2 }],
  ["ir", "to go", "eer", "verb", null, "verbs", "Voy al trabajo.", "I'm going to work.", { antonyms: ["venir"], difficulty: 2 }],
  ["querer", "to want / to love", "ke-RER", "verb", null, "verbs", "Quiero un vaso de agua.", "I want a glass of water."],
  ["poder", "to be able to / can", "po-DER", "verb", null, "verbs", "¿Puedes ayudarme?", "Can you help me?"],
  ["hablar", "to speak", "a-BLAR", "verb", null, "verbs", "Hablo un poco de español.", "I speak a little Spanish."],
  ["comer", "to eat", "ko-MER", "verb", null, "verbs", "Comemos a las dos.", "We eat at two."],
  ["vivir", "to live", "bee-BEER", "verb", null, "verbs", "Vivo en Madrid.", "I live in Madrid."],
  ["saber", "to know (facts)", "sa-BER", "verb", null, "verbs", "No sé la respuesta.", "I don't know the answer.", { related: ["conocer"] }],
  ["conocer", "to know (people/places)", "ko-no-THER", "verb", null, "verbs", "Conozco a su hermana.", "I know his sister.", { related: ["saber"] }],
  ["necesitar", "to need", "ne-the-see-TAR", "verb", null, "verbs", "Necesito ayuda.", "I need help."],
  ["gustar", "to be pleasing (to like)", "goos-TAR", "verb", null, "verbs", "Me gusta el café.", "I like coffee.", { difficulty: 3 }],
  ["trabajar", "to work", "tra-ba-HAR", "verb", null, "verbs", "Trabajo en una oficina.", "I work in an office."],
  ["estudiar", "to study", "es-too-DYAR", "verb", null, "verbs", "Estudio español.", "I study Spanish."],
  ["beber", "to drink", "be-BER", "verb", null, "verbs", "Bebo agua.", "I drink water.", { synonyms: ["tomar"] }],

  // People & family
  ["la familia", "family", "la fa-MEE-lya", "noun", "f", "family", "Mi familia es grande.", "My family is big."],
  ["la madre", "mother", "la MA-dre", "noun", "f", "family", "Mi madre se llama Ana.", "My mother's name is Ana.", { synonyms: ["mamá"], antonyms: ["padre"] }],
  ["el padre", "father", "el PA-dre", "noun", "m", "family", "Mi padre trabaja mucho.", "My father works a lot.", { synonyms: ["papá"], antonyms: ["madre"] }],
  ["el hermano", "brother", "el er-MA-no", "noun", "m", "family", "Tengo un hermano mayor.", "I have an older brother."],
  ["la hermana", "sister", "la er-MA-na", "noun", "f", "family", "Mi hermana estudia medicina.", "My sister studies medicine."],
  ["el hijo", "son", "el EE-ho", "noun", "m", "family", "Su hijo tiene cinco años.", "Her son is five."],
  ["la hija", "daughter", "la EE-ha", "noun", "f", "family", "Mi hija va al colegio.", "My daughter goes to school."],
  ["el amigo", "friend (male)", "el a-MEE-go", "noun", "m", "people", "Es mi mejor amigo.", "He's my best friend."],
  ["la amiga", "friend (female)", "la a-MEE-ga", "noun", "f", "people", "Voy con una amiga.", "I'm going with a friend."],
  ["el hombre", "man", "el OM-bre", "noun", "m", "people", "El hombre de la tienda es amable.", "The man in the shop is kind.", { antonyms: ["mujer"] }],
  ["la mujer", "woman / wife", "la moo-HER", "noun", "f", "people", "Esa mujer es mi jefa.", "That woman is my boss.", { antonyms: ["hombre"] }],
  ["el niño", "child / boy", "el NEE-nyo", "noun", "m", "people", "El niño juega en el parque.", "The boy plays in the park."],
  ["el nombre", "name", "el NOM-bre", "noun", "m", "basics", "¿Cuál es tu nombre?", "What's your name?"],

  // Numbers
  ["uno", "one", "OO-no", "number", null, "numbers", "Solo tengo uno.", "I only have one."],
  ["dos", "two", "dos", "number", null, "numbers", "Dos cafés, por favor.", "Two coffees, please.", { pluralForm: null }],
  ["tres", "three", "tres", "number", null, "numbers", "Son las tres.", "It's three o'clock.", { pluralForm: null }],
  ["cuatro", "four", "KWA-tro", "number", null, "numbers", "Tengo cuatro clases hoy.", "I have four classes today."],
  ["cinco", "five", "THEEN-ko", "number", null, "numbers", "Cinco euros.", "Five euros."],
  ["seis", "six", "seys", "number", null, "numbers", "Seis personas.", "Six people.", { pluralForm: null }],
  ["siete", "seven", "SYE-te", "number", null, "numbers", "Siete días.", "Seven days."],
  ["ocho", "eight", "O-cho", "number", null, "numbers", "Ocho horas de trabajo.", "Eight hours of work."],
  ["nueve", "nine", "NWE-be", "number", null, "numbers", "Nueve de la mañana.", "Nine in the morning."],
  ["diez", "ten", "dyeth", "number", null, "numbers", "Diez minutos.", "Ten minutes."],
  ["veinte", "twenty", "BEYN-te", "number", null, "numbers", "Tengo veinte años.", "I'm twenty years old."],
  ["cien", "one hundred", "thyen", "number", null, "numbers", "Cien euros.", "One hundred euros."],

  // Food & drink
  ["la comida", "food / meal", "la ko-MEE-da", "noun", "f", "food", "La comida está lista.", "The food is ready."],
  ["el agua", "water", "el A-gwa", "noun", "f", "food", "Un vaso de agua, por favor.", "A glass of water, please.", { pluralForm: "las aguas", difficulty: 3 }],
  ["el café", "coffee", "el ka-FE", "noun", "m", "food", "Tomo café con leche.", "I have coffee with milk.", { pluralForm: "los cafés" }],
  ["el pan", "bread", "el pan", "noun", "m", "food", "Compro pan cada mañana.", "I buy bread every morning."],
  ["la leche", "milk", "la LE-che", "noun", "f", "food", "No me gusta la leche fría.", "I don't like cold milk."],
  ["el vino", "wine", "el BEE-no", "noun", "m", "food", "Un vino tinto, por favor.", "A red wine, please."],
  ["la cerveza", "beer", "la ther-BE-tha", "noun", "f", "food", "Dos cervezas, por favor.", "Two beers, please."],
  ["la carne", "meat", "la KAR-ne", "noun", "f", "food", "No como carne.", "I don't eat meat."],
  ["el pescado", "fish (as food)", "el pes-KA-do", "noun", "m", "food", "El pescado está muy fresco.", "The fish is very fresh."],
  ["la fruta", "fruit", "la FROO-ta", "noun", "f", "food", "Como fruta todos los días.", "I eat fruit every day."],
  ["el restaurante", "restaurant", "el res-tow-RAN-te", "noun", "m", "food", "Vamos a un restaurante.", "Let's go to a restaurant."],
  ["la cuenta", "the bill", "la KWEN-ta", "noun", "f", "food", "La cuenta, por favor.", "The bill, please."],

  // Time & days
  ["el día", "day", "el DEE-a", "noun", "m", "time", "Todos los días estudio.", "I study every day.", { pluralForm: "los días" }],
  ["la semana", "week", "la se-MA-na", "noun", "f", "time", "La semana que viene.", "Next week."],
  ["el año", "year", "el A-nyo", "noun", "m", "time", "Este año aprendo español.", "This year I'm learning Spanish."],
  ["la hora", "hour / time", "la O-ra", "noun", "f", "time", "¿Qué hora es?", "What time is it?"],
  ["hoy", "today", "oy", "adverb", null, "time", "Hoy no trabajo.", "I'm not working today."],
  ["mañana", "tomorrow / morning", "ma-NYA-na", "adverb", null, "time", "Mañana voy a Madrid.", "Tomorrow I'm going to Madrid.", { antonyms: ["ayer"] }],
  ["ayer", "yesterday", "a-YER", "adverb", null, "time", "Ayer fue lunes.", "Yesterday was Monday.", { antonyms: ["mañana"] }],
  ["ahora", "now", "a-O-ra", "adverb", null, "time", "Ahora no puedo.", "I can't right now."],
  ["siempre", "always", "SYEM-pre", "adverb", null, "time", "Siempre llego tarde.", "I'm always late.", { antonyms: ["nunca"] }],
  ["nunca", "never", "NOON-ka", "adverb", null, "time", "Nunca he estado allí.", "I've never been there.", { antonyms: ["siempre"] }],
  ["el lunes", "Monday", "el LOO-nes", "noun", "m", "time", "El lunes empiezo el curso.", "On Monday I start the course.", { pluralForm: "los lunes" }],

  // Places & everyday objects
  ["la casa", "house / home", "la KA-sa", "noun", "f", "places", "Estoy en casa.", "I'm at home."],
  ["la ciudad", "city", "la thyoo-DAD", "noun", "f", "places", "Madrid es una ciudad grande.", "Madrid is a big city."],
  ["la calle", "street", "la KA-ye", "noun", "f", "places", "Vivo en esta calle.", "I live on this street."],
  ["el trabajo", "work / job", "el tra-BA-ho", "noun", "m", "work", "Voy al trabajo en metro.", "I go to work by metro."],
  ["la tienda", "shop", "la TYEN-da", "noun", "f", "shopping", "La tienda abre a las nueve.", "The shop opens at nine."],
  ["el dinero", "money", "el dee-NE-ro", "noun", "m", "shopping", "No tengo dinero.", "I don't have any money."],
  ["el coche", "car", "el KO-che", "noun", "m", "travel", "Voy en coche.", "I'm going by car.", { region: "es-ES", regionalVariant: "el carro", synonyms: ["el carro", "el auto"] }],
  ["el carro", "car (Latin America)", "el KA-rro", "noun", "m", "travel", "Mi carro está en el taller.", "My car is at the garage.", { region: "es-419", regionalVariant: "el coche", synonyms: ["el coche"] }],
  ["el libro", "book", "el LEE-bro", "noun", "m", "objects", "Leo un libro cada mes.", "I read a book every month."],
  ["el teléfono", "telephone", "el te-LE-fo-no", "noun", "m", "objects", "Mi teléfono no funciona.", "My phone isn't working."],

  // High-frequency adjectives & function words
  ["bueno", "good", "BWE-no", "adjective", null, "adjectives", "Es un buen restaurante.", "It's a good restaurant.", { antonyms: ["malo"] }],
  ["malo", "bad", "MA-lo", "adjective", null, "adjectives", "Hace mal tiempo.", "The weather is bad.", { antonyms: ["bueno"] }],
  ["grande", "big", "GRAN-de", "adjective", null, "adjectives", "Una casa grande.", "A big house.", { antonyms: ["pequeño"] }],
  ["pequeño", "small", "pe-KE-nyo", "adjective", null, "adjectives", "Un piso pequeño.", "A small flat.", { antonyms: ["grande"] }],
  ["nuevo", "new", "NWE-bo", "adjective", null, "adjectives", "Tengo un trabajo nuevo.", "I have a new job.", { antonyms: ["viejo"] }],
  ["mucho", "much / a lot", "MOO-cho", "adjective", null, "quantity", "Trabajo mucho.", "I work a lot.", { antonyms: ["poco"] }],
  ["poco", "little / few", "PO-ko", "adjective", null, "quantity", "Hablo un poco de español.", "I speak a little Spanish.", { antonyms: ["mucho"] }],
  ["muy", "very", "mwee", "adverb", null, "quantity", "Estoy muy cansado.", "I'm very tired."],
  ["también", "also / too", "tam-BYEN", "adverb", null, "basics", "Yo también.", "Me too.", { antonyms: ["tampoco"] }],
  ["pero", "but", "PE-ro", "conjunction", null, "connectors", "Quiero ir, pero no puedo.", "I want to go, but I can't."],
  ["porque", "because", "POR-ke", "conjunction", null, "connectors", "No voy porque estoy enfermo.", "I'm not going because I'm ill."],
  ["cansado", "tired", "kan-SA-do", "adjective", null, "feelings", "Estoy muy cansado hoy.", "I'm very tired today."],
  ["contento", "happy / pleased", "kon-TEN-to", "adjective", null, "feelings", "Estoy contenta con el resultado.", "I'm pleased with the result.", { synonyms: ["feliz"], antonyms: ["triste"] }],
  ["barato", "cheap", "ba-RA-to", "adjective", null, "shopping", "Es más barato en el mercado.", "It's cheaper at the market.", { antonyms: ["caro"] }],
  ["caro", "expensive", "KA-ro", "adjective", null, "shopping", "Este móvil es muy caro.", "This phone is very expensive.", { antonyms: ["barato"] }],
  // Concrete everyday nouns — high-frequency and easy to picture, which is what
  // makes them the right words to attach memory hooks to.
  ["el perro", "dog", "el PE-rro", "noun", "m", "animals", "Mi perro se llama Toby.", "My dog is called Toby."],
  ["el gato", "cat", "el GA-to", "noun", "m", "animals", "El gato duerme en el sofá.", "The cat sleeps on the sofa."],
  ["el caballo", "horse", "el ka-BA-yo", "noun", "m", "animals", "Monta a caballo los domingos.", "He rides a horse on Sundays."],
  ["la mesa", "table", "la ME-sa", "noun", "f", "objects", "La mesa es de madera.", "The table is made of wood."],
  ["la silla", "chair", "la SEE-ya", "noun", "f", "objects", "Siéntate en esta silla.", "Sit on this chair."],
  ["la llave", "key", "la YA-be", "noun", "f", "objects", "He perdido las llaves.", "I have lost my keys."],
  ["el reloj", "watch / clock", "el re-LOH", "noun", "m", "objects", "Mi reloj está roto.", "My watch is broken.", { pluralForm: "los relojes" }],
  ["el zapato", "shoe", "el tha-PA-to", "noun", "m", "clothing", "Estos zapatos son muy cómodos.", "These shoes are very comfortable."],
  ["el queso", "cheese", "el KE-so", "noun", "m", "food", "Me gusta el queso manchego.", "I like manchego cheese."],
  ["la mano", "hand", "la MA-no", "noun", "f", "body", "Dame la mano.", "Give me your hand.", { difficulty: 2 }],
  ["el problema", "problem", "el pro-BLE-ma", "noun", "m", "abstract", "No hay ningún problema.", "There is no problem at all.", { difficulty: 2 }],
];
