import type { Row } from "./row.js";

export const A2_ROWS: Row[] = [
  ["el viaje", "trip / journey", "el BYA-he", "noun", "m", "travel", "El viaje dura tres horas.", "The trip takes three hours."],
  ["el billete", "ticket", "el bee-YE-te", "noun", "m", "travel", "Compré un billete de ida y vuelta.", "I bought a return ticket.", { region: "es-ES", regionalVariant: "el boleto" }],
  ["el aeropuerto", "airport", "el a-e-ro-PWER-to", "noun", "m", "travel", "Llegamos al aeropuerto a las seis.", "We got to the airport at six."],
  ["el equipaje", "luggage", "el e-kee-PA-he", "noun", "m", "travel", "Perdieron mi equipaje.", "They lost my luggage."],
  ["alojarse", "to stay (lodging)", "a-lo-HAR-se", "verb", null, "travel", "Nos alojamos en un hostal.", "We stayed in a guesthouse."],
  ["reservar", "to book / reserve", "re-ser-BAR", "verb", null, "travel", "He reservado una mesa para dos.", "I've booked a table for two."],
  ["el hotel", "hotel", "el o-TEL", "noun", "m", "travel", "El hotel está en el centro.", "The hotel is in the centre."],
  ["la habitación", "room", "la a-bee-ta-THYON", "noun", "f", "travel", "Una habitación doble, por favor.", "A double room, please."],
  ["probarse", "to try on", "pro-BAR-se", "verb", null, "shopping", "¿Me puedo probar esta camisa?", "Can I try this shirt on?"],
  ["la talla", "size (clothing)", "la TA-ya", "noun", "f", "shopping", "¿Qué talla usas?", "What size do you take?"],
  ["la ropa", "clothes", "la RO-pa", "noun", "f", "shopping", "Necesito ropa de invierno.", "I need winter clothes."],
  ["el descuento", "discount", "el des-KWEN-to", "noun", "m", "shopping", "Hay un descuento del veinte por ciento.", "There's a twenty percent discount."],
  ["la empresa", "company", "la em-PRE-sa", "noun", "f", "work", "Trabajo en una empresa pequeña.", "I work at a small company."],
  ["la reunión", "meeting", "la re-oo-NYON", "noun", "f", "work", "Tengo una reunión a las diez.", "I have a meeting at ten."],
  ["el sueldo", "salary", "el SWEL-do", "noun", "m", "work", "El sueldo no está mal.", "The salary isn't bad.", { synonyms: ["el salario"] }],
  ["el horario", "schedule / hours", "el o-RA-ryo", "noun", "m", "work", "Tengo un horario flexible.", "I have flexible hours."],
  ["la salud", "health", "la sa-LOOD", "noun", "f", "health", "La salud es lo más importante.", "Health is the most important thing."],
  ["doler", "to hurt", "do-LER", "verb", null, "health", "Me duele la cabeza.", "My head hurts.", { difficulty: 3 }],
  ["la cabeza", "head", "la ka-BE-tha", "noun", "f", "health", "Me duele la cabeza.", "I have a headache."],
  ["el médico", "doctor", "el ME-dee-ko", "noun", "m", "health", "Tengo cita con el médico.", "I have a doctor's appointment.", { synonyms: ["el doctor"] }],
  ["enfermo", "ill / sick", "en-FER-mo", "adjective", null, "health", "Estoy enfermo desde el lunes.", "I've been ill since Monday.", { antonyms: ["sano"] }],
  ["la cita", "appointment / date", "la THEE-ta", "noun", "f", "health", "Pedí cita para el martes.", "I made an appointment for Tuesday."],
  ["la pareja", "partner / couple", "la pa-RE-ha", "noun", "f", "relationships", "Vivo con mi pareja.", "I live with my partner."],
  ["casarse", "to get married", "ka-SAR-se", "verb", null, "relationships", "Se casaron el año pasado.", "They got married last year."],
  ["el novio", "boyfriend", "el NO-byo", "noun", "m", "relationships", "Su novio es argentino.", "Her boyfriend is Argentinian."],
  ["conocerse", "to meet each other", "ko-no-THER-se", "verb", null, "relationships", "Nos conocimos en la universidad.", "We met at university."],
  ["quedar", "to arrange to meet", "ke-DAR", "verb", null, "relationships", "¿Quedamos a las ocho?", "Shall we meet at eight?", { region: "es-ES" }],
  ["ayer por la noche", "last night", "a-YER por la NO-che", "phrase", null, "time", "Ayer por la noche vi una película.", "Last night I watched a film."],
  ["el año pasado", "last year", "el A-nyo pa-SA-do", "phrase", null, "time", "El año pasado viajé a México.", "Last year I travelled to Mexico."],
  ["luego", "later / then", "LWE-go", "adverb", null, "connectors", "Primero comemos y luego salimos.", "First we eat and then we go out."],
  ["entonces", "then / so", "en-TON-thes", "adverb", null, "connectors", "Entonces, ¿qué hacemos?", "So, what do we do?"],
  ["además", "besides / moreover", "a-de-MAS", "adverb", null, "connectors", "Además, es más barato.", "Besides, it's cheaper."],
  ["aunque", "although", "OWN-ke", "conjunction", null, "connectors", "Aunque llueve, salimos.", "Although it's raining, we're going out."],
  ["parecer", "to seem", "pa-re-THER", "verb", null, "verbs", "Me parece bien.", "That seems fine to me."],
  ["intentar", "to try", "een-ten-TAR", "verb", null, "verbs", "Voy a intentarlo otra vez.", "I'm going to try again.", { synonyms: ["probar"] }],
  ["olvidar", "to forget", "ol-bee-DAR", "verb", null, "verbs", "Olvidé las llaves.", "I forgot the keys.", { antonyms: ["recordar"] }],
  ["recordar", "to remember", "re-kor-DAR", "verb", null, "verbs", "No recuerdo su nombre.", "I don't remember his name.", { antonyms: ["olvidar"] }],
  ["echar de menos", "to miss (someone)", "e-CHAR de ME-nos", "phrase", null, "feelings", "Echo de menos a mi familia.", "I miss my family.", { region: "es-ES", regionalVariant: "extrañar" }],
  // False friends. These earn their place because the mistake is not "wrong
  // word" but "confidently wrong word" — the learner has no reason to doubt it.
  ["embarazada", "pregnant", "em-ba-ra-THA-da", "adjective", null, "false_friends", "Mi hermana está embarazada.", "My sister is pregnant."],
  ["la librería", "bookshop", "la lee-bre-REE-a", "noun", "f", "false_friends", "Compré el libro en una librería.", "I bought the book at a bookshop."],
  ["actualmente", "currently", "ak-twal-MEN-te", "adverb", null, "false_friends", "Actualmente vivo en Madrid.", "I currently live in Madrid."],
  ["asistir", "to attend", "a-sees-TEER", "verb", null, "false_friends", "Voy a asistir a la reunión.", "I am going to attend the meeting."],
  ["el éxito", "success", "el EK-see-to", "noun", "m", "false_friends", "La película fue un gran éxito.", "The film was a big success."],
  ["sensible", "sensitive", "sen-SEE-ble", "adjective", null, "false_friends", "Es muy sensible a las críticas.", "He is very sensitive to criticism."],
  ["molestar", "to bother", "mo-les-TAR", "verb", null, "false_friends", "Perdona, ¿te molesto?", "Sorry, am I bothering you?"],
  ["la carpeta", "folder", "la kar-PE-ta", "noun", "f", "false_friends", "Guarda los documentos en esa carpeta.", "Keep the documents in that folder."],
  ["constipado", "having a cold", "kons-tee-PA-do", "adjective", null, "false_friends", "Estoy constipado y me duele la garganta.", "I have a cold and my throat hurts."],
];
