import type { Row } from "./row.js";

export const A2_ROWS: Row[] = [
  ["el viaje", "trip / journey", "el BYA-he", "noun", "m", "travel", "El viaje dura tres horas.", "The trip takes three hours."],
  ["el billete", "ticket", "el bee-YE-te", "noun", "m", "travel", "Compré un billete de ida y vuelta.", "I bought a return ticket.", { region: "es-ES", regionalVariant: "el boleto" }],
  ["el aeropuerto", "airport", "el a-e-ro-PWER-to", "noun", "m", "travel", "Llegamos al aeropuerto a las seis.", "We got to the airport at six."],
  ["el equipaje", "luggage", "el e-kee-PA-he", "noun", "m", "travel", "Perdieron mi equipaje.", "They lost my luggage."],
  ["alojarse", "to stay (lodging)", "a-lo-HAR-se", "verb", null, "travel", "Nos alojamos en un hostal.", "We stayed in a guesthouse."],
  ["reservar", "to book / reserve", "re-ser-BAR", "verb", null, "travel", "He reservado una mesa para dos.", "I've booked a table for two."],
  ["el hotel", "hotel", "el o-TEL", "noun", "m", "travel", "El hotel está en el centro.", "The hotel is in the centre."],
  ["la habitación", "room", "la a-bee-ta-THYON", "noun", "f", "travel", "Una habitación doble, por favor.", "A double room, please."],
  ["probarse", "to try on", "pro-BAR-se", "verb", null, "shopping", "¿Me puedo probar esta camisa?", "Can I try this shirt on?"],
  ["la talla", "size (clothing)", "la TA-ya", "noun", "f", "shopping", "¿Qué talla usas?", "What size do you take?"],
  ["la ropa", "clothes", "la RO-pa", "noun", "f", "shopping", "Necesito ropa de invierno.", "I need winter clothes."],
  ["el descuento", "discount", "el des-KWEN-to", "noun", "m", "shopping", "Hay un descuento del veinte por ciento.", "There's a twenty percent discount."],
  ["la empresa", "company", "la em-PRE-sa", "noun", "f", "work", "Trabajo en una empresa pequeña.", "I work at a small company."],
  ["la reunión", "meeting", "la re-oo-NYON", "noun", "f", "work", "Tengo una reunión a las diez.", "I have a meeting at ten."],
  ["el sueldo", "salary", "el SWEL-do", "noun", "m", "work", "El sueldo no está mal.", "The salary isn't bad.", { synonyms: ["el salario"] }],
  ["el horario", "schedule / hours", "el o-RA-ryo", "noun", "m", "work", "Tengo un horario flexible.", "I have flexible hours."],
  ["la salud", "health", "la sa-LOOD", "noun", "f", "health", "La salud es lo más importante.", "Health is the most important thing."],
  ["doler", "to hurt", "do-LER", "verb", null, "health", "Me duele la cabeza.", "My head hurts.", { difficulty: 3 }],
  ["la cabeza", "head", "la ka-BE-tha", "noun", "f", "health", "Me duele la cabeza.", "I have a headache."],
  ["el médico", "doctor", "el ME-dee-ko", "noun", "m", "health", "Tengo cita con el médico.", "I have a doctor's appointment.", { synonyms: ["el doctor"] }],
  ["enfermo", "ill / sick", "en-FER-mo", "adjective", null, "health", "Estoy enfermo desde el lunes.", "I've been ill since Monday.", { antonyms: ["sano"] }],
  ["la cita", "appointment / date", "la THEE-ta", "noun", "f", "health", "Pedí cita para el martes.", "I made an appointment for Tuesday."],
  ["la pareja", "partner / couple", "la pa-RE-ha", "noun", "f", "relationships", "Vivo con mi pareja.", "I live with my partner."],
  ["casarse", "to get married", "ka-SAR-se", "verb", null, "relationships", "Se casaron el año pasado.", "They got married last year."],
  ["el novio", "boyfriend", "el NO-byo", "noun", "m", "relationships", "Su novio es argentino.", "Her boyfriend is Argentinian."],
  ["conocerse", "to meet each other", "ko-no-THER-se", "verb", null, "relationships", "Nos conocimos en la universidad.", "We met at university."],
  ["quedar", "to arrange to meet", "ke-DAR", "verb", null, "relationships", "¿Quedamos a las ocho?", "Shall we meet at eight?", { region: "es-ES" }],
  ["ayer por la noche", "last night", "a-YER por la NO-che", "phrase", null, "time", "Ayer por la noche vi una película.", "Last night I watched a film."],
  ["el año pasado", "last year", "el A-nyo pa-SA-do", "phrase", null, "time", "El año pasado viajé a México.", "Last year I travelled to Mexico."],
  ["luego", "later / then", "LWE-go", "adverb", null, "connectors", "Primero comemos y luego salimos.", "First we eat and then we go out."],
  ["entonces", "then / so", "en-TON-thes", "adverb", null, "connectors", "Entonces, ¿qué hacemos?", "So, what do we do?"],
  ["además", "besides / moreover", "a-de-MAS", "adverb", null, "connectors", "Además, es más barato.", "Besides, it's cheaper."],
  ["aunque", "although", "OWN-ke", "conjunction", null, "connectors", "Aunque llueve, salimos.", "Although it's raining, we're going out."],
  ["parecer", "to seem", "pa-re-THER", "verb", null, "verbs", "Me parece bien.", "That seems fine to me."],
  ["intentar", "to try", "een-ten-TAR", "verb", null, "verbs", "Voy a intentarlo otra vez.", "I'm going to try again.", { synonyms: ["probar"] }],
  ["olvidar", "to forget", "ol-bee-DAR", "verb", null, "verbs", "Olvidé las llaves.", "I forgot the keys.", { antonyms: ["recordar"] }],
  ["recordar", "to remember", "re-kor-DAR", "verb", null, "verbs", "No recuerdo su nombre.", "I don't remember his name.", { antonyms: ["olvidar"] }],
  ["echar de menos", "to miss (someone)", "e-CHAR de ME-nos", "phrase", null, "feelings", "Echo de menos a mi familia.", "I miss my family.", { region: "es-ES", regionalVariant: "extrañar" }],
  // False friends. These earn their place because the mistake is not "wrong
  // word" but "confidently wrong word" — the learner has no reason to doubt it.
  ["embarazada", "pregnant", "em-ba-ra-THA-da", "adjective", null, "false_friends", "Mi hermana está embarazada.", "My sister is pregnant."],
  ["la librería", "bookshop", "la lee-bre-REE-a", "noun", "f", "false_friends", "Compré el libro en una librería.", "I bought the book at a bookshop."],
  ["actualmente", "currently", "ak-twal-MEN-te", "adverb", null, "false_friends", "Actualmente vivo en Madrid.", "I currently live in Madrid."],
  ["asistir", "to attend", "a-sees-TEER", "verb", null, "false_friends", "Voy a asistir a la reunión.", "I am going to attend the meeting."],
  ["el éxito", "success", "el EK-see-to", "noun", "m", "false_friends", "La película fue un gran éxito.", "The film was a big success."],
  ["sensible", "sensitive", "sen-SEE-ble", "adjective", null, "false_friends", "Es muy sensible a las críticas.", "He is very sensitive to criticism."],
  ["molestar", "to bother", "mo-les-TAR", "verb", null, "false_friends", "Perdona, ¿te molesto?", "Sorry, am I bothering you?"],
  ["la carpeta", "folder", "la kar-PE-ta", "noun", "f", "false_friends", "Guarda los documentos en esa carpeta.", "Keep the documents in that folder."],
  ["constipado", "having a cold", "kons-tee-PA-do", "adjective", null, "false_friends", "Estoy constipado y me duele la garganta.", "I have a cold and my throat hurts."],
  // ─── Food & eating out ────────────────────────────────────────────────────
  ["el desayuno", "breakfast", "el de-sa-YOO-no", "noun", "m", "food", "El desayuno está incluido.", "Breakfast is included."],
  ["la cena", "dinner", "la THE-na", "noun", "f", "food", "La cena es a las nueve.", "Dinner is at nine."],
  ["el almuerzo", "lunch", "el al-MWER-tho", "noun", "m", "food", "El almuerzo dura una hora.", "Lunch lasts an hour."],
  ["el plato", "dish / plate", "el PLA-to", "noun", "m", "food", "Este plato es típico de aquí.", "This dish is typical of here."],
  ["la bebida", "drink", "la be-BEE-da", "noun", "f", "food", "¿Qué bebida quieres?", "What drink would you like?"],
  ["el postre", "dessert", "el POS-tre", "noun", "m", "food", "De postre quiero helado.", "For dessert I want ice cream."],
  ["la verdura", "vegetable", "la ber-DOO-ra", "noun", "f", "food", "Como verdura todos los días.", "I eat vegetables every day."],
  ["el arroz", "rice", "el a-RROTH", "noun", "m", "food", "El arroz está en su punto.", "The rice is perfectly cooked.", { pluralForm: "los arroces" }],
  ["el huevo", "egg", "el WE-bo", "noun", "m", "food", "Quiero dos huevos fritos.", "I want two fried eggs."],
  ["el aceite", "oil", "el a-THEY-te", "noun", "m", "food", "El aceite de oliva es caro.", "Olive oil is expensive."],
  ["la sal", "salt", "la sal", "noun", "f", "food", "Falta sal en la sopa.", "The soup needs salt."],
  ["el azúcar", "sugar", "el a-THOO-kar", "noun", "m", "food", "No tomo azúcar en el café.", "I do not take sugar in coffee."],
  ["probar", "to try / to taste", "pro-BAR", "verb", null, "food", "¿Quieres probar el gazpacho?", "Do you want to try the gazpacho?"],
  ["pedir", "to order / to ask for", "pe-DEER", "verb", null, "food", "Voy a pedir la cuenta.", "I am going to ask for the bill."],
  ["servir", "to serve", "ser-BEER", "verb", null, "food", "Sirven comida hasta las once.", "They serve food until eleven."],

  // ─── The city & getting around ────────────────────────────────────────────
  ["la esquina", "corner", "la es-KEE-na", "noun", "f", "places", "Gira en la esquina.", "Turn at the corner."],
  ["el semáforo", "traffic light", "el se-MA-fo-ro", "noun", "m", "travel", "Para en el semáforo.", "Stop at the traffic light."],
  ["la parada", "stop", "la pa-RA-da", "noun", "f", "travel", "La parada está enfrente.", "The stop is opposite."],
  ["el andén", "platform", "el an-DEN", "noun", "m", "travel", "El tren sale del andén tres.", "The train leaves from platform three.", { pluralForm: "los andenes" }],
  ["la maleta", "suitcase", "la ma-LE-ta", "noun", "f", "travel", "Mi maleta pesa mucho.", "My suitcase is very heavy."],
  ["el retraso", "delay", "el re-TRA-so", "noun", "m", "travel", "El vuelo lleva dos horas de retraso.", "The flight is two hours delayed."],
  ["la llegada", "arrival", "la ye-GA-da", "noun", "f", "travel", "La llegada está prevista a las seis.", "Arrival is scheduled for six.", { antonyms: ["la salida"] }],
  ["la salida", "exit / departure", "la sa-LEE-da", "noun", "f", "travel", "La salida está a la derecha.", "The exit is on the right.", { antonyms: ["la llegada"] }],
  ["el barrio", "neighbourhood", "el BA-rryo", "noun", "m", "places", "Vivo en un barrio tranquilo.", "I live in a quiet neighbourhood."],
  ["el edificio", "building", "el e-dee-FEE-thyo", "noun", "m", "places", "El edificio es muy antiguo.", "The building is very old."],
  ["girar", "to turn", "hee-RAR", "verb", null, "travel", "Gira a la izquierda.", "Turn left."],
  ["seguir", "to follow / to continue", "se-GEER", "verb", null, "travel", "Sigue recto dos calles.", "Carry straight on for two streets."],
  ["cruzar", "to cross", "kroo-THAR", "verb", null, "travel", "Cruza la plaza y verás el museo.", "Cross the square and you will see the museum."],
  ["la izquierda", "left", "la eeth-KYER-da", "noun", "f", "travel", "Está a la izquierda.", "It is on the left.", { antonyms: ["la derecha"] }],
  ["la derecha", "right", "la de-RE-cha", "noun", "f", "travel", "Gira a la derecha.", "Turn right.", { antonyms: ["la izquierda"] }],

  // ─── Technology & everyday admin ──────────────────────────────────────────
  ["el ordenador", "computer", "el or-de-na-DOR", "noun", "m", "technology", "Mi ordenador va muy lento.", "My computer is very slow.", { region: "es-ES", regionalVariant: "la computadora" }],
  ["la computadora", "computer (Latin America)", "la kom-poo-ta-DO-ra", "noun", "f", "technology", "La computadora no enciende.", "The computer will not turn on.", { region: "es-419", regionalVariant: "el ordenador" }],
  ["el móvil", "mobile phone", "el MO-beel", "noun", "m", "technology", "Se me quedó sin batería el móvil.", "My mobile ran out of battery.", { region: "es-ES", regionalVariant: "el celular", pluralForm: "los móviles" }],
  ["el celular", "mobile phone (Latin America)", "el the-loo-LAR", "noun", "m", "technology", "Te escribo desde el celular.", "I am writing to you from my mobile.", { region: "es-419", regionalVariant: "el móvil" }],
  ["el correo", "email / post", "el ko-RRE-o", "noun", "m", "technology", "Te mando un correo esta tarde.", "I will send you an email this afternoon."],
  ["la contraseña", "password", "la kon-tra-SE-nya", "noun", "f", "technology", "He olvidado la contraseña.", "I have forgotten the password."],
  ["la pantalla", "screen", "la pan-TA-ya", "noun", "f", "technology", "La pantalla está rota.", "The screen is broken."],
  ["descargar", "to download", "des-kar-GAR", "verb", null, "technology", "Voy a descargar la aplicación.", "I am going to download the app."],
  ["encender", "to turn on", "en-then-DER", "verb", null, "technology", "Enciende la luz, por favor.", "Turn on the light, please.", { antonyms: ["apagar"] }],
  ["apagar", "to turn off", "a-pa-GAR", "verb", null, "technology", "Apaga el móvil en el cine.", "Turn your phone off in the cinema.", { antonyms: ["encender"] }],
  ["el documento", "document", "el do-koo-MEN-to", "noun", "m", "admin", "Necesito firmar el documento.", "I need to sign the document."],
  ["firmar", "to sign", "feer-MAR", "verb", null, "admin", "Firme aquí, por favor.", "Sign here, please."],
  ["el pasaporte", "passport", "el pa-sa-POR-te", "noun", "m", "travel", "¿Me enseña el pasaporte?", "May I see your passport?"],

  // ─── Daily routine ────────────────────────────────────────────────────────
  ["levantarse", "to get up", "le-ban-TAR-se", "verb", null, "routine", "Me levanto a las siete.", "I get up at seven.", { antonyms: ["acostarse"] }],
  ["acostarse", "to go to bed", "a-kos-TAR-se", "verb", null, "routine", "Me acuesto tarde los viernes.", "I go to bed late on Fridays.", { antonyms: ["levantarse"] }],
  ["ducharse", "to have a shower", "doo-CHAR-se", "verb", null, "routine", "Me ducho por la mañana.", "I shower in the morning."],
  ["vestirse", "to get dressed", "bes-TEER-se", "verb", null, "routine", "Me visto rápido.", "I get dressed quickly."],
  ["desayunar", "to have breakfast", "de-sa-yoo-NAR", "verb", null, "routine", "Desayuno café y tostada.", "I have coffee and toast for breakfast."],
  ["descansar", "to rest", "des-kan-SAR", "verb", null, "routine", "Necesito descansar un rato.", "I need to rest for a while."],
  ["limpiar", "to clean", "leem-PYAR", "verb", null, "routine", "Limpio la casa los sábados.", "I clean the house on Saturdays."],
  ["lavar", "to wash", "la-BAR", "verb", null, "routine", "Lavo los platos después de cenar.", "I wash the dishes after dinner."],

  // ─── Feelings & people ────────────────────────────────────────────────────
  ["triste", "sad", "TREES-te", "adjective", null, "feelings", "Está triste por la noticia.", "She is sad about the news.", { antonyms: ["alegre"] }],
  ["alegre", "cheerful", "a-LE-gre", "adjective", null, "feelings", "Es una persona muy alegre.", "He is a very cheerful person.", { antonyms: ["triste"] }],
  ["enfadado", "angry", "en-fa-DA-do", "adjective", null, "feelings", "Está enfadado conmigo.", "He is angry with me.", { region: "es-ES", regionalVariant: "enojado" }],
  ["nervioso", "nervous", "ner-BYO-so", "adjective", null, "feelings", "Estoy nervioso por el examen.", "I am nervous about the exam.", { antonyms: ["tranquilo"] }],
  ["tranquilo", "calm", "tran-KEE-lo", "adjective", null, "feelings", "Tranquilo, no pasa nada.", "Relax, it is fine.", { antonyms: ["nervioso"] }],
  ["preocupado", "worried", "pre-o-koo-PA-do", "adjective", null, "feelings", "Estoy preocupada por mi madre.", "I am worried about my mother."],
  ["sorprendido", "surprised", "sor-pren-DEE-do", "adjective", null, "feelings", "Me quedé sorprendido.", "I was surprised."],
  ["orgulloso", "proud", "or-goo-YO-so", "adjective", null, "feelings", "Estoy orgulloso de ti.", "I am proud of you."],
  ["amable", "kind", "a-MA-ble", "adjective", null, "people", "Es muy amable con todos.", "He is very kind to everyone.", { synonyms: ["simpático"] }],
  ["simpático", "friendly / likeable", "seem-PA-tee-ko", "adjective", null, "people", "Tu hermana es muy simpática.", "Your sister is very friendly.", { antonyms: ["antipático"] }],
  ["el compañero", "colleague / classmate", "el kom-pa-NYE-ro", "noun", "m", "people", "Mi compañero de trabajo me ayudó.", "My colleague helped me."],
  ["el vecino", "neighbour", "el be-THEE-no", "noun", "m", "people", "El vecino de arriba hace ruido.", "The neighbour upstairs makes noise."],
  ["el jefe", "boss", "el HE-fe", "noun", "m", "work", "Hablé con mi jefe ayer.", "I spoke to my boss yesterday."],
  ["el cliente", "customer", "el KLYEN-te", "noun", "m", "work", "El cliente siempre pregunta lo mismo.", "The customer always asks the same thing."],

  // ─── Work & study ─────────────────────────────────────────────────────────
  ["la entrevista", "interview", "la en-tre-BEES-ta", "noun", "f", "work", "Tengo una entrevista el martes.", "I have an interview on Tuesday."],
  ["el contrato", "contract", "el kon-TRA-to", "noun", "m", "work", "Firmé el contrato la semana pasada.", "I signed the contract last week."],
  ["el sueño", "dream / sleepiness", "el SWE-nyo", "noun", "m", "abstract", "Tengo mucho sueño.", "I am very sleepy."],
  ["la carrera", "degree / career", "la ka-RRE-ra", "noun", "f", "education", "Estudié la carrera en Salamanca.", "I did my degree in Salamanca."],
  ["el examen", "exam", "el ek-SA-men", "noun", "m", "education", "El examen fue muy largo.", "The exam was very long.", { pluralForm: "los exámenes" }],
  ["la nota", "mark / note", "la NO-ta", "noun", "f", "education", "Saqué buena nota.", "I got a good mark."],
  ["aprobar", "to pass", "a-pro-BAR", "verb", null, "education", "Aprobé el examen de conducir.", "I passed my driving test.", { antonyms: ["suspender"] }],
  ["suspender", "to fail", "sus-pen-DER", "verb", null, "education", "Suspendí matemáticas.", "I failed maths.", { antonyms: ["aprobar"], region: "es-ES" }],
  ["ganar", "to earn / to win", "ga-NAR", "verb", null, "work", "Gana bastante en ese puesto.", "She earns quite a lot in that job.", { antonyms: ["perder"] }],
  ["perder", "to lose / to miss", "per-DER", "verb", null, "verbs", "Perdí el tren.", "I missed the train.", { antonyms: ["ganar", "encontrar"] }],

  // ─── Shopping & money ─────────────────────────────────────────────────────
  ["el precio", "price", "el PRE-thyo", "noun", "m", "shopping", "El precio incluye el IVA.", "The price includes VAT."],
  ["la tarjeta", "card", "la tar-HE-ta", "noun", "f", "shopping", "¿Puedo pagar con tarjeta?", "Can I pay by card?"],
  ["el efectivo", "cash", "el e-fek-TEE-bo", "noun", "m", "shopping", "Solo aceptan efectivo.", "They only accept cash."],
  ["la factura", "invoice / bill", "la fak-TOO-ra", "noun", "f", "shopping", "Necesito la factura.", "I need the invoice."],
  ["gastar", "to spend", "gas-TAR", "verb", null, "shopping", "Gasto demasiado en libros.", "I spend too much on books.", { antonyms: ["ahorrar"] }],
  ["ahorrar", "to save", "a-o-RRAR", "verb", null, "shopping", "Ahorro para un viaje.", "I am saving for a trip.", { antonyms: ["gastar"] }],
  ["devolver", "to return / to give back", "de-bol-BER", "verb", null, "shopping", "Quiero devolver esta camisa.", "I want to return this shirt."],
  ["el regalo", "present", "el re-GA-lo", "noun", "m", "shopping", "Le compré un regalo a mi madre.", "I bought my mother a present."],

  // ─── Health ───────────────────────────────────────────────────────────────
  ["la fiebre", "fever", "la FYE-bre", "noun", "f", "health", "Tengo fiebre desde ayer.", "I have had a fever since yesterday."],
  ["la receta", "prescription / recipe", "la re-THE-ta", "noun", "f", "health", "El médico me dio una receta.", "The doctor gave me a prescription."],
  ["la farmacia", "pharmacy", "la far-MA-thya", "noun", "f", "health", "La farmacia cierra a las diez.", "The pharmacy closes at ten."],
  ["la pastilla", "pill", "la pas-TEE-ya", "noun", "f", "health", "Tomo una pastilla al día.", "I take one pill a day."],
  ["el dolor", "pain", "el do-LOR", "noun", "m", "health", "Tengo dolor de espalda.", "I have back pain.", { pluralForm: "los dolores" }],
  ["cuidar", "to look after", "kwee-DAR", "verb", null, "health", "Cuida a sus padres.", "She looks after her parents."],
  ["mejorar", "to improve", "me-ho-RAR", "verb", null, "health", "Espero que mejores pronto.", "I hope you get better soon.", { antonyms: ["empeorar"] }],

  // ─── Connectors & useful phrases ──────────────────────────────────────────
  ["por eso", "that is why", "por E-so", "phrase", null, "connectors", "Llovía, por eso no salimos.", "It was raining, that is why we did not go out."],
  ["en cambio", "on the other hand", "en KAM-byo", "phrase", null, "connectors", "Él es tranquilo; ella, en cambio, es nerviosa.", "He is calm; she, on the other hand, is nervous."],
  ["por supuesto", "of course", "por soo-PWES-to", "phrase", null, "expressions", "Por supuesto que te ayudo.", "Of course I will help you.", { synonyms: ["claro"] }],
  ["a veces", "sometimes", "a BE-thes", "phrase", null, "time", "A veces trabajo desde casa.", "Sometimes I work from home."],
  ["en seguida", "right away", "en se-GEE-da", "phrase", null, "time", "Vuelvo en seguida.", "I will be right back."],
  ["ahora mismo", "right now", "a-O-ra MEES-mo", "phrase", null, "time", "Lo hago ahora mismo.", "I am doing it right now."],
  ["poco a poco", "little by little", "PO-ko a PO-ko", "phrase", null, "expressions", "Poco a poco voy entendiendo.", "Little by little I am understanding."],
  ["sobre todo", "above all", "SO-bre TO-do", "phrase", null, "connectors", "Me gusta viajar, sobre todo en tren.", "I like travelling, above all by train."],
  ["tener ganas de", "to feel like", "te-NER GA-nas de", "phrase", null, "expressions", "Tengo ganas de verte.", "I feel like seeing you."],
  ["acabar de", "to have just", "a-ka-BAR de", "phrase", null, "expressions", "Acabo de llegar.", "I have just arrived."],
  ["volver a", "to do again", "bol-BER a", "phrase", null, "expressions", "Vuelve a leerlo.", "Read it again."],
  ["ponerse de acuerdo", "to reach an agreement", "po-NER-se de a-KWER-do", "phrase", null, "expressions", "No conseguimos ponernos de acuerdo.", "We could not reach an agreement."],
  // ─── Leisure, culture & small talk ────────────────────────────────────────
  ["la película", "film", "la pe-LEE-koo-la", "noun", "f", "culture", "La película dura dos horas.", "The film lasts two hours."],
  ["el concierto", "concert", "el kon-THYER-to", "noun", "m", "culture", "El concierto empieza a las nueve.", "The concert starts at nine."],
  ["la entrada", "ticket / entrance", "la en-TRA-da", "noun", "f", "culture", "Compré dos entradas por internet.", "I bought two tickets online."],
  ["el museo", "museum", "el moo-SE-o", "noun", "m", "culture", "El museo abre los domingos.", "The museum opens on Sundays."],
  ["la exposición", "exhibition", "la eks-po-see-THYON", "noun", "f", "culture", "La exposición cierra en junio.", "The exhibition closes in June."],
  ["el equipo", "team / equipment", "el e-KEE-po", "noun", "m", "sport", "Mi equipo ganó el domingo.", "My team won on Sunday."],
  ["el partido", "match / political party", "el par-TEE-do", "noun", "m", "sport", "El partido acabó en empate.", "The match ended in a draw."],
  ["entrenar", "to train", "en-tre-NAR", "verb", null, "sport", "Entreno tres veces por semana.", "I train three times a week."],
  ["quedarse", "to stay / to remain", "ke-DAR-se", "verb", null, "verbs", "Me quedé en casa todo el finde.", "I stayed home all weekend."],
  ["disfrutar", "to enjoy", "dees-froo-TAR", "verb", null, "verbs", "Disfruté mucho del viaje.", "I really enjoyed the trip."],
  ["aburrirse", "to get bored", "a-boo-RREER-se", "verb", null, "verbs", "Me aburrí en la charla.", "I got bored during the talk."],
  ["reírse", "to laugh", "rre-EER-se", "verb", null, "verbs", "Nos reímos toda la noche.", "We laughed all night."],
  ["el ambiente", "atmosphere / vibe", "el am-BYEN-te", "noun", "m", "culture", "El bar tiene buen ambiente.", "The bar has a good atmosphere."],
  ["la costumbre", "custom / habit", "la kos-TOOM-bre", "noun", "f", "culture", "Es costumbre cenar tarde aquí.", "It is customary to eat late here."],
  ["el ruido", "noise", "el RRWEE-do", "noun", "m", "everyday", "Hay mucho ruido en la calle.", "There is a lot of noise in the street.", { antonyms: ["el silencio"] }],
  ["el silencio", "silence", "el see-LEN-thyo", "noun", "m", "everyday", "Se hizo el silencio en la sala.", "Silence fell in the room.", { antonyms: ["el ruido"] }],
  ["la suerte", "luck", "la SWER-te", "noun", "f", "abstract", "¡Qué suerte has tenido!", "How lucky you were!"],
  ["la broma", "joke", "la BRO-ma", "noun", "f", "culture", "Solo era una broma.", "It was only a joke."],
  ["el consejo", "piece of advice", "el kon-SE-ho", "noun", "m", "abstract", "Te doy un consejo.", "Let me give you a piece of advice."],
  ["la razón", "reason", "la rra-THON", "noun", "f", "abstract", "Tienes razón.", "You are right.", { pluralForm: "las razones" }],
  ["la manera", "way / manner", "la ma-NE-ra", "noun", "f", "abstract", "No hay manera de convencerlo.", "There is no way to convince him.", { synonyms: ["la forma"] }],
  ["el motivo", "reason / motive", "el mo-TEE-bo", "noun", "m", "abstract", "¿Cuál es el motivo del retraso?", "What is the reason for the delay?"],
  ["mientras tanto", "meanwhile", "MYEN-tras TAN-to", "phrase", null, "time", "Mientras tanto, prepara la mesa.", "Meanwhile, set the table."],
  ["cada vez más", "more and more", "KA-da beth mas", "phrase", null, "expressions", "Cada vez más gente estudia en línea.", "More and more people study online."],
  ["¿qué tal si...?", "how about...?", "ke tal see", "phrase", null, "expressions", "¿Qué tal si quedamos el jueves?", "How about we meet on Thursday?"],
  ["me da igual", "I do not mind", "me da ee-GWAL", "phrase", null, "expressions", "Me da igual dónde comamos.", "I do not mind where we eat."],
  ["no pasa nada", "it is fine / no problem", "no PA-sa NA-da", "phrase", null, "expressions", "Llegas tarde, pero no pasa nada.", "You are late, but it is fine."],
  ["estar de acuerdo", "to agree", "es-TAR de a-KWER-do", "phrase", null, "expressions", "Estoy de acuerdo contigo.", "I agree with you."],
  ["darse prisa", "to hurry", "DAR-se PREE-sa", "phrase", null, "expressions", "Date prisa, que cierran.", "Hurry up, they are closing."],
  ["hacer cola", "to queue", "a-THER KO-la", "phrase", null, "expressions", "Hicimos cola media hora.", "We queued for half an hour."],

  // ─── Referenced by other entries as synonyms, antonyms and variants ───────
  ["comenzar", "to begin", "ko-men-THAR", "verb", null, "verbs", "La clase comienza a las diez.", "The class begins at ten.", { synonyms: ["empezar"] }],
  ["aún", "still / yet", "a-OON", "adverb", null, "time", "Aún no ha llegado.", "He has not arrived yet."],
  ["el salario", "salary", "el sa-LA-ryo", "noun", "m", "work", "El salario se paga a fin de mes.", "The salary is paid at the end of the month.", { synonyms: ["el sueldo"] }],
  ["el doctor", "doctor", "el dok-TOR", "noun", "m", "health", "El doctor me recetó antibióticos.", "The doctor prescribed me antibiotics.", { synonyms: ["el médico"] }],
  ["sano", "healthy", "SA-no", "adjective", null, "health", "Lleva una vida sana.", "She leads a healthy life.", { antonyms: ["enfermo"] }],
  ["empeorar", "to get worse", "em-pe-o-RAR", "verb", null, "verbs", "El tiempo empeoró por la tarde.", "The weather got worse in the afternoon.", { antonyms: ["mejorar"] }],
  ["generoso", "generous", "he-ne-RO-so", "adjective", null, "people", "Fue muy generoso con nosotros.", "He was very generous with us."],
];
