import type { Row } from "./row.js";

export const B1_ROWS: Row[] = [
  ["el desarrollo", "development", "el de-sa-RRO-yo", "noun", "m", "abstract", "El desarrollo del proyecto va bien.", "The project's development is going well."],
  ["la propuesta", "proposal", "la pro-PWES-ta", "noun", "f", "work", "Presentaron una propuesta interesante.", "They presented an interesting proposal."],
  ["lograr", "to achieve / manage to", "lo-GRAR", "verb", null, "verbs", "Logró aprobar el examen.", "He managed to pass the exam.", { synonyms: ["conseguir"] }],
  ["suponer", "to suppose / entail", "soo-po-NER", "verb", null, "verbs", "Supongo que tienes razón.", "I suppose you're right."],
  ["exigir", "to demand / require", "ek-see-HEER", "verb", null, "verbs", "El trabajo exige mucha paciencia.", "The job requires a lot of patience."],
  ["el ámbito", "sphere / field", "el AM-bee-to", "noun", "m", "abstract", "En el ámbito laboral es distinto.", "In the workplace it's different."],
  ["el hecho", "fact", "el E-cho", "noun", "m", "abstract", "El hecho es que no hay dinero.", "The fact is there's no money."],
  ["a pesar de", "in spite of", "a pe-SAR de", "phrase", null, "connectors", "A pesar de todo, seguimos.", "In spite of everything, we carry on."],
  ["sin embargo", "however", "seen em-BAR-go", "phrase", null, "connectors", "Es caro; sin embargo, merece la pena.", "It's expensive; however, it's worth it."],
  ["por lo tanto", "therefore", "por lo TAN-to", "phrase", null, "connectors", "No estudió; por lo tanto, suspendió.", "He didn't study; therefore he failed."],
  ["en cuanto a", "as for / regarding", "en KWAN-to a", "phrase", null, "connectors", "En cuanto al precio, es negociable.", "As for the price, it's negotiable."],
  ["el medio ambiente", "the environment", "el ME-dyo am-BYEN-te", "noun", "m", "society", "Hay que cuidar el medio ambiente.", "We must look after the environment."],
  ["la huelga", "strike", "la WEL-ga", "noun", "f", "society", "Los médicos están en huelga.", "The doctors are on strike."],
  ["el paro", "unemployment", "el PA-ro", "noun", "m", "society", "El paro juvenil sigue alto.", "Youth unemployment remains high.", { region: "es-ES", regionalVariant: "el desempleo" }],
  ["la encuesta", "survey / poll", "la en-KWES-ta", "noun", "f", "society", "Según la encuesta, la mayoría está a favor.", "According to the poll, most are in favour."],
  ["soler", "to usually do", "so-LER", "verb", null, "verbs", "Suelo levantarme temprano.", "I usually get up early.", { difficulty: 4 }],
  ["darse cuenta", "to realise", "DAR-se KWEN-ta", "phrase", null, "verbs", "No me di cuenta del error.", "I didn't realise the mistake."],
  ["hacer falta", "to be necessary", "a-THER FAL-ta", "phrase", null, "verbs", "Hace falta más tiempo.", "More time is needed."],
  ["merecer la pena", "to be worth it", "me-re-THER la PE-na", "phrase", null, "expressions", "Merece la pena verlo.", "It's worth seeing.", { region: "es-ES", regionalVariant: "valer la pena" }],
  ["estar harto de", "to be fed up with", "es-TAR AR-to de", "phrase", null, "expressions", "Estoy harto de esperar.", "I'm fed up with waiting."],
  ["dar igual", "not to matter", "dar ee-GWAL", "phrase", null, "expressions", "Me da igual.", "I don't mind either way."],
  ["por si acaso", "just in case", "por see a-KA-so", "phrase", null, "expressions", "Lleva paraguas por si acaso.", "Take an umbrella just in case."],
  ["de repente", "suddenly", "de re-PEN-te", "phrase", null, "expressions", "De repente empezó a llover.", "Suddenly it started to rain."],
  ["el guion", "script", "el gee-ON", "noun", "m", "culture", "El guion de la película es original.", "The film's script is original."],
  // ─── Work, money & society ────────────────────────────────────────────────
  ["el presupuesto", "budget", "el pre-soo-PWES-to", "noun", "m", "work", "El presupuesto se aprobó por poco.", "The budget was approved by a narrow margin."],
  ["la plantilla", "staff / template", "la plan-TEE-ya", "noun", "f", "work", "La empresa redujo la plantilla.", "The company cut its staff."],
  ["el convenio", "collective agreement", "el kon-BE-nyo", "noun", "m", "work", "El convenio regula el horario.", "The agreement governs working hours."],
  ["la jornada", "working day", "la hor-NA-da", "noun", "f", "work", "Trabajo a jornada completa.", "I work full time."],
  ["ascender", "to be promoted / to rise", "as-then-DER", "verb", null, "work", "La ascendieron a directora.", "She was promoted to director."],
  ["desempeñar", "to carry out (a role)", "des-em-pe-NYAR", "verb", null, "work", "Desempeña un papel clave.", "He plays a key role."],
  ["la inversión", "investment", "la een-ber-SYON", "noun", "f", "economy", "La inversión extranjera creció.", "Foreign investment grew.", { pluralForm: "las inversiones" }],
  ["la deuda", "debt", "la DEW-da", "noun", "f", "economy", "El país renegoció su deuda.", "The country renegotiated its debt."],
  ["el impuesto", "tax", "el eem-PWES-to", "noun", "m", "economy", "Subieron los impuestos.", "Taxes went up."],
  ["el crecimiento", "growth", "el kre-thee-MYEN-to", "noun", "m", "economy", "El crecimiento se ha frenado.", "Growth has slowed."],
  ["la crisis", "crisis", "la KREE-sees", "noun", "f", "economy", "La crisis afectó a todo el sector.", "The crisis hit the whole sector.", { pluralForm: "las crisis" }],
  ["invertir", "to invest", "een-ber-TEER", "verb", null, "economy", "Invirtieron en energías limpias.", "They invested in clean energy."],
  ["ahorrarse", "to spare oneself", "a-o-RRAR-se", "verb", null, "expressions", "Ahórrate el comentario.", "Spare me the comment."],

  // ─── Politics, media & public life ────────────────────────────────────────
  ["el gobierno", "government", "el go-BYER-no", "noun", "m", "politics", "El gobierno anunció medidas.", "The government announced measures."],
  ["la ley", "law", "la ley", "noun", "f", "politics", "La ley entra en vigor mañana.", "The law comes into force tomorrow.", { pluralForm: "las leyes" }],
  ["la medida", "measure", "la me-DEE-da", "noun", "f", "politics", "Es una medida polémica.", "It is a controversial measure."],
  ["el acuerdo", "agreement", "el a-KWER-do", "noun", "m", "politics", "Llegaron a un acuerdo.", "They reached an agreement."],
  ["la campaña", "campaign", "la kam-PA-nya", "noun", "f", "politics", "La campaña duró tres semanas.", "The campaign lasted three weeks."],
  ["el ciudadano", "citizen", "el thyoo-da-DA-no", "noun", "m", "politics", "Los ciudadanos salieron a la calle.", "Citizens took to the streets."],
  ["la ciudadanía", "citizenry / citizenship", "la thyoo-da-da-NEE-a", "noun", "f", "politics", "La ciudadanía exige explicaciones.", "The public is demanding explanations."],
  ["el titular", "headline", "el tee-too-LAR", "noun", "m", "media", "El titular exagera la noticia.", "The headline exaggerates the story."],
  ["la fuente", "source", "la FWEN-te", "noun", "f", "media", "Según fuentes oficiales, hubo acuerdo.", "According to official sources, there was an agreement."],
  ["denunciar", "to report / to denounce", "de-noon-THYAR", "verb", null, "media", "Denunciaron el caso ante la policía.", "They reported the case to the police."],
  ["destacar", "to stand out / to highlight", "des-ta-KAR", "verb", null, "media", "Cabe destacar un dato.", "One figure is worth highlighting."],
  ["señalar", "to point out", "se-nya-LAR", "verb", null, "media", "El informe señala varios fallos.", "The report points out several failings."],
  ["advertir", "to warn / to notice", "ad-ber-TEER", "verb", null, "verbs", "Los expertos advierten del riesgo.", "Experts are warning of the risk."],

  // ─── Environment, science & health ────────────────────────────────────────
  ["el cambio climático", "climate change", "el KAM-byo klee-MA-tee-ko", "phrase", null, "environment", "El cambio climático ya se nota.", "Climate change is already noticeable."],
  ["los residuos", "waste", "los rre-SEE-dwos", "noun", "m", "environment", "Reciclamos los residuos orgánicos.", "We recycle organic waste."],
  ["la sequía", "drought", "la se-KEE-a", "noun", "f", "environment", "La sequía afecta al campo.", "The drought is affecting farmland."],
  ["el consumo", "consumption", "el kon-SOO-mo", "noun", "m", "environment", "Hay que reducir el consumo de agua.", "Water consumption must be reduced."],
  ["renovable", "renewable", "rre-no-BA-ble", "adjective", null, "environment", "Apuestan por energías renovables.", "They are betting on renewable energy."],
  ["la investigación", "research / investigation", "la een-bes-tee-ga-THYON", "noun", "f", "science", "La investigación duró dos años.", "The research took two years."],
  ["el estudio", "study", "el es-TOO-dyo", "noun", "m", "science", "Un estudio reciente lo confirma.", "A recent study confirms it."],
  ["el dato", "piece of data", "el DA-to", "noun", "m", "science", "Los datos no son concluyentes.", "The data are not conclusive."],
  ["comprobar", "to check / to verify", "kom-pro-BAR", "verb", null, "verbs", "Habría que comprobar la fuente.", "The source would need checking."],
  ["el tratamiento", "treatment", "el tra-ta-MYEN-to", "noun", "m", "health", "El tratamiento dura un mes.", "The treatment lasts a month."],
  ["el riesgo", "risk", "el RRYES-go", "noun", "m", "abstract", "Corres el riesgo de perderlo todo.", "You run the risk of losing everything."],
  ["prevenir", "to prevent", "pre-be-NEER", "verb", null, "health", "Más vale prevenir que curar.", "Prevention is better than cure."],
  ["agotado", "exhausted / sold out", "a-go-TA-do", "adjective", null, "health", "Llegué agotado a casa.", "I got home exhausted."],

  // ─── Character & behaviour ────────────────────────────────────────────────
  ["exigente", "demanding", "ek-see-HEN-te", "adjective", null, "people", "Es un jefe muy exigente.", "He is a very demanding boss."],
  ["testarudo", "stubborn", "tes-ta-ROO-do", "adjective", null, "people", "No discutas, es testaruda.", "Do not argue, she is stubborn.", { synonyms: ["cabezota"] }],
  ["fiable", "reliable", "FYA-ble", "adjective", null, "people", "Es una fuente fiable.", "It is a reliable source.", { region: "es-ES", regionalVariant: "confiable" }],
  ["comprensivo", "understanding", "kom-pren-SEE-bo", "adjective", null, "people", "Mi tutora fue muy comprensiva.", "My tutor was very understanding.", { difficulty: 3 }],
  ["egoísta", "selfish", "e-go-EES-ta", "adjective", null, "people", "No seas egoísta.", "Do not be selfish.", { antonyms: ["generoso"] }],
  ["atrevido", "daring / cheeky", "a-tre-BEE-do", "adjective", null, "people", "Fue una decisión atrevida.", "It was a daring decision."],
  ["el comportamiento", "behaviour", "el kom-por-ta-MYEN-to", "noun", "m", "people", "Su comportamiento sorprendió a todos.", "Their behaviour surprised everyone."],
  ["el ánimo", "spirits / encouragement", "el A-nee-mo", "noun", "m", "feelings", "Está bajo de ánimo últimamente.", "He has been in low spirits lately."],
  ["el orgullo", "pride", "el or-GOO-yo", "noun", "m", "feelings", "El orgullo no le deja pedir perdón.", "Pride stops him from apologising."],
  ["la vergüenza", "embarrassment / shame", "la ber-GWEN-tha", "noun", "f", "feelings", "Me da vergüenza hablar en público.", "I am embarrassed to speak in public."],
  ["el asombro", "amazement", "el a-SOM-bro", "noun", "m", "feelings", "Lo miró con asombro.", "She looked at him in amazement."],

  // ─── Abstract nouns & useful verbs ────────────────────────────────────────
  ["el rasgo", "feature / trait", "el RRAS-go", "noun", "m", "abstract", "Es un rasgo típico del sur.", "It is a typical feature of the south."],
  ["la ventaja", "advantage", "la ben-TA-ha", "noun", "f", "abstract", "La principal ventaja es el precio.", "The main advantage is the price.", { antonyms: ["el inconveniente"] }],
  ["el inconveniente", "drawback", "el een-kon-be-NYEN-te", "noun", "m", "abstract", "El único inconveniente es la distancia.", "The only drawback is the distance.", { antonyms: ["la ventaja"] }],
  ["la finalidad", "purpose", "la fee-na-lee-DAD", "noun", "f", "abstract", "¿Cuál es la finalidad del proyecto?", "What is the purpose of the project?"],
  ["el plazo", "deadline / period", "el PLA-tho", "noun", "m", "abstract", "El plazo termina el viernes.", "The deadline is Friday."],
  ["la clave", "key / crucial point", "la KLA-be", "noun", "f", "abstract", "La clave está en la práctica.", "The key is practice."],
  ["el reto", "challenge", "el RRE-to", "noun", "m", "abstract", "Aceptó el reto sin dudar.", "She accepted the challenge without hesitating.", { synonyms: ["el desafío"] }],
  ["la falta", "lack / fault", "la FAL-ta", "noun", "f", "abstract", "Fue por falta de tiempo.", "It was for lack of time."],
  ["planteado", "posed / raised", "plan-te-A-do", "adjective", null, "abstract", "El problema está bien planteado.", "The problem is well framed."],
  ["aportar", "to contribute", "a-por-TAR", "verb", null, "verbs", "Cada uno aportó una idea.", "Each of us contributed an idea."],
  ["fomentar", "to encourage / to promote", "fo-men-TAR", "verb", null, "verbs", "El programa fomenta la lectura.", "The programme promotes reading."],
  ["impedir", "to prevent", "eem-pe-DEER", "verb", null, "verbs", "La lluvia impidió el partido.", "The rain prevented the match."],
  ["conseguir", "to manage / to obtain", "kon-se-GEER", "verb", null, "verbs", "Conseguí entradas para el concierto.", "I managed to get concert tickets.", { synonyms: ["lograr"] }],
  ["atreverse", "to dare", "a-tre-BER-se", "verb", null, "verbs", "No me atreví a preguntar.", "I did not dare to ask."],
  ["quejarse", "to complain", "ke-HAR-se", "verb", null, "verbs", "Se queja de todo.", "He complains about everything."],
  ["arrepentirse", "to regret", "a-rre-pen-TEER-se", "verb", null, "verbs", "Me arrepiento de no haber ido.", "I regret not having gone."],
  ["enterarse", "to find out", "en-te-RAR-se", "verb", null, "verbs", "Me enteré por la prensa.", "I found out from the press."],
  ["fijarse", "to notice / to pay attention", "fee-HAR-se", "verb", null, "verbs", "Fíjate en el detalle.", "Notice the detail."],
  ["surgir", "to arise", "soor-HEER", "verb", null, "verbs", "Surgió un imprevisto.", "Something unexpected came up."],
  ["plantear", "to raise / to pose", "plan-te-AR", "verb", null, "verbs", "Planteó una pregunta incómoda.", "She raised an awkward question."],
  ["reflejar", "to reflect / to show", "rre-fle-HAR", "verb", null, "verbs", "La encuesta refleja el descontento.", "The survey reflects the discontent."],
  ["resultar", "to turn out", "rre-sool-TAR", "verb", null, "verbs", "Resultó ser más fácil de lo previsto.", "It turned out easier than expected."],
  ["suponer un reto", "to be a challenge", "soo-po-NER oon RRE-to", "phrase", null, "expressions", "El cambio supuso un reto enorme.", "The change was an enormous challenge."],

  // ─── Discourse markers ────────────────────────────────────────────────────
  ["por otro lado", "on the other hand", "por O-tro LA-do", "phrase", null, "connectors", "Por otro lado, sale más barato.", "On the other hand, it works out cheaper."],
  ["es decir", "that is to say", "es de-THEER", "phrase", null, "connectors", "Llega el martes, es decir, pasado mañana.", "He arrives Tuesday, that is, the day after tomorrow."],
  ["de hecho", "in fact", "de E-cho", "phrase", null, "connectors", "De hecho, ya lo había leído.", "In fact, I had already read it."],
  ["en realidad", "actually", "en rre-a-lee-DAD", "phrase", null, "connectors", "En realidad no me molesta.", "It does not actually bother me."],
  ["a partir de", "from (a point) onwards", "a par-TEER de", "phrase", null, "connectors", "A partir de mañana cambia el horario.", "From tomorrow the timetable changes."],
  ["a lo largo de", "throughout", "a lo LAR-go de", "phrase", null, "connectors", "A lo largo del año hubo mejoras.", "There were improvements throughout the year."],
  ["en función de", "depending on", "en foonk-THYON de", "phrase", null, "connectors", "El precio varía en función del destino.", "The price varies depending on the destination."],
  ["por lo visto", "apparently", "por lo BEES-to", "phrase", null, "connectors", "Por lo visto, se han mudado.", "Apparently they have moved."],
  ["al fin y al cabo", "after all", "al feen ee al KA-bo", "phrase", null, "connectors", "Al fin y al cabo, es su decisión.", "After all, it is their decision."],
  ["cabe destacar", "it is worth noting", "KA-be des-ta-KAR", "phrase", null, "connectors", "Cabe destacar el esfuerzo del equipo.", "The team's effort is worth noting.", { difficulty: 4 }],
  ["hoy en día", "these days", "oy en DEE-a", "phrase", null, "time", "Hoy en día todo se hace en línea.", "These days everything is done online."],
  ["a medida que", "as (progressively)", "a me-DEE-da ke", "phrase", null, "connectors", "A medida que practicas, mejoras.", "As you practise, you improve."],

  // ─── Idioms that carry meaning, not decoration ────────────────────────────
  ["echar una mano", "to lend a hand", "e-CHAR OO-na MA-no", "phrase", null, "expressions", "¿Me echas una mano?", "Can you give me a hand?"],
  ["tener en cuenta", "to bear in mind", "te-NER en KWEN-ta", "phrase", null, "expressions", "Ten en cuenta el horario.", "Bear the timetable in mind."],
  ["hacer caso", "to pay attention / to obey", "a-THER KA-so", "phrase", null, "expressions", "No le hagas caso.", "Do not pay any attention to him."],
  ["ponerse al día", "to catch up", "po-NER-se al DEE-a", "phrase", null, "expressions", "Necesito ponerme al día con el temario.", "I need to catch up on the syllabus."],
  ["dar la lata", "to pester", "dar la LA-ta", "phrase", null, "expressions", "Los niños llevan toda la tarde dando la lata.", "The children have been pestering all afternoon.", { region: "es-ES" }],
  ["quedarse en blanco", "to go blank", "ke-DAR-se en BLAN-ko", "phrase", null, "expressions", "Me quedé en blanco en el examen.", "I went blank in the exam."],
  ["salir adelante", "to get by / to pull through", "sa-LEER a-de-LAN-te", "phrase", null, "expressions", "La familia salió adelante como pudo.", "The family pulled through as best it could."],
  ["tomar una decisión", "to make a decision", "to-MAR OO-na de-thee-SYON", "phrase", null, "expressions", "Hay que tomar una decisión ya.", "A decision has to be made now."],
  // ─── Housing, law & everyday bureaucracy ──────────────────────────────────
  ["el alquiler", "rent", "el al-kee-LER", "noun", "m", "housing", "El alquiler ha subido otra vez.", "The rent has gone up again."],
  ["el inquilino", "tenant", "el een-kee-LEE-no", "noun", "m", "housing", "El inquilino avisó con un mes.", "The tenant gave a month's notice."],
  ["la hipoteca", "mortgage", "la ee-po-TE-ka", "noun", "f", "housing", "Terminamos de pagar la hipoteca.", "We finished paying off the mortgage."],
  ["el trámite", "formality / procedure", "el TRA-mee-te", "noun", "m", "admin", "El trámite se hace por internet.", "The procedure is done online."],
  ["el plazo de entrega", "delivery deadline", "el PLA-tho de en-TRE-ga", "phrase", null, "admin", "El plazo de entrega es de dos semanas.", "The delivery time is two weeks."],
  ["solicitar", "to apply for", "so-lee-thee-TAR", "verb", null, "admin", "Solicité una beca.", "I applied for a grant."],
  ["rellenar", "to fill in", "rre-ye-NAR", "verb", null, "admin", "Rellene el formulario, por favor.", "Please fill in the form.", { region: "es-ES", regionalVariant: "llenar" }],
  ["el seguro", "insurance", "el se-GOO-ro", "noun", "m", "admin", "El seguro cubre los daños.", "The insurance covers the damage."],
  ["el juicio", "trial / judgement", "el HWEE-thyo", "noun", "m", "politics", "El juicio se celebra en marzo.", "The trial takes place in March."],
  ["la multa", "fine", "la MOOL-ta", "noun", "f", "admin", "Me pusieron una multa por aparcar mal.", "I got a fine for parking badly."],
  ["el derecho", "right / law", "el de-RE-cho", "noun", "m", "politics", "Tiene derecho a un abogado.", "He has the right to a lawyer."],
  ["el deber", "duty", "el de-BER", "noun", "m", "politics", "Votar es un deber cívico.", "Voting is a civic duty."],
  ["cumplir", "to fulfil / to comply", "koom-PLEER", "verb", null, "verbs", "No cumplieron lo prometido.", "They did not deliver on what they promised."],
  ["incumplir", "to breach", "een-koom-PLEER", "verb", null, "verbs", "Incumplió el contrato.", "He breached the contract.", { antonyms: ["cumplir"] }],
  ["disponer de", "to have available", "dees-po-NER de", "phrase", null, "expressions", "Dispone de un mes para recurrir.", "You have one month to appeal."],
  ["cabezota", "stubborn (colloquial)", "ka-be-THO-ta", "adjective", null, "people", "Mi hermano es un cabezota.", "My brother is so stubborn.", { region: "es-ES" }],
  ["el desafío", "challenge", "el de-sa-FEE-o", "noun", "m", "abstract", "Asumieron el desafío con calma.", "They took on the challenge calmly."],
];
