import type { Row } from "./row.js";

export const B2_ROWS: Row[] = [
  ["el planteamiento", "approach / framing", "el plan-te-a-MYEN-to", "noun", "m", "abstract", "No comparto su planteamiento.", "I don't share his approach."],
  ["cuestionar", "to question / challenge", "kwes-tyo-NAR", "verb", null, "debate", "Nadie cuestionó la decisión.", "Nobody questioned the decision."],
  ["matizar", "to qualify / nuance", "ma-tee-THAR", "verb", null, "debate", "Quisiera matizar lo que dije.", "I'd like to qualify what I said."],
  ["el matiz", "nuance", "el ma-TEETH", "noun", "m", "debate", "Es un matiz importante.", "It's an important nuance.", { pluralForm: "los matices" }],
  ["asumir", "to take on / assume", "a-soo-MEER", "verb", null, "work", "Asumió la responsabilidad.", "She took on the responsibility."],
  ["el enfoque", "focus / angle", "el en-FO-ke", "noun", "m", "abstract", "Necesitamos otro enfoque.", "We need a different angle."],
  ["por consiguiente", "consequently", "por kon-see-GYEN-te", "phrase", null, "connectors", "Por consiguiente, se aplazó la reunión.", "Consequently, the meeting was postponed."],
  ["no obstante", "nevertheless", "no obs-TAN-te", "phrase", null, "connectors", "No obstante, hay excepciones.", "Nevertheless, there are exceptions."],
  ["siempre y cuando", "provided that", "SYEM-pre ee KWAN-do", "phrase", null, "connectors", "Iré siempre y cuando me avises.", "I'll go provided you let me know."],
  ["la brecha", "gap / divide", "la BRE-cha", "noun", "f", "society", "La brecha salarial persiste.", "The pay gap persists."],
  ["el sesgo", "bias", "el SES-go", "noun", "m", "society", "El estudio tiene un sesgo evidente.", "The study has an obvious bias."],
  ["desarrollarse", "to unfold / develop", "de-sa-rro-YAR-se", "verb", null, "abstract", "El debate se desarrolló con calma.", "The debate unfolded calmly."],
  ["imprescindible", "essential", "eem-pres-theen-DEE-ble", "adjective", null, "adjectives", "Es imprescindible reservar.", "Booking is essential."],
  ["polémico", "controversial", "po-LE-mee-ko", "adjective", null, "adjectives", "Fue una decisión polémica.", "It was a controversial decision."],
  ["a raíz de", "as a result of", "a ra-EETH de", "phrase", null, "connectors", "A raíz del incidente, cambiaron las normas.", "As a result of the incident, the rules changed."],
  ["dar por sentado", "to take for granted", "dar por sen-TA-do", "phrase", null, "expressions", "No des por sentado su apoyo.", "Don't take their support for granted."],
  ["llevarse bien", "to get on well", "ye-BAR-se byen", "phrase", null, "relationships", "Me llevo bien con mis compañeros.", "I get on well with my colleagues."],
  ["poner en duda", "to cast doubt on", "po-NER en DOO-da", "phrase", null, "debate", "Puso en duda las cifras.", "He cast doubt on the figures."],
  // ─── Argument & analysis ──────────────────────────────────────────────────
  ["el argumento", "argument / plot", "el ar-goo-MEN-to", "noun", "m", "abstract", "Su argumento no se sostiene.", "His argument does not hold up."],
  ["la premisa", "premise", "la pre-MEE-sa", "noun", "f", "abstract", "Parte de una premisa falsa.", "It starts from a false premise."],
  ["la evidencia", "evidence", "la e-bee-DEN-thya", "noun", "f", "abstract", "No hay evidencia que lo respalde.", "There is no evidence to support it."],
  ["respaldar", "to back / to support", "rres-pal-DAR", "verb", null, "verbs", "Los datos respaldan la hipótesis.", "The data back the hypothesis."],
  ["refutar", "to refute", "rre-foo-TAR", "verb", null, "verbs", "Refutó cada uno de los puntos.", "She refuted each of the points."],
  ["sostener", "to maintain / to hold", "sos-te-NER", "verb", null, "verbs", "Sostiene que la ley es injusta.", "He maintains that the law is unjust."],
  ["contrastar", "to contrast / to verify", "kon-tras-TAR", "verb", null, "verbs", "Conviene contrastar las fuentes.", "It is advisable to cross-check the sources."],
  ["desmentir", "to deny / to debunk", "des-men-TEER", "verb", null, "verbs", "El ministerio desmintió la noticia.", "The ministry denied the story."],
  ["constatar", "to confirm / to note", "kons-ta-TAR", "verb", null, "verbs", "Se constata una mejora leve.", "A slight improvement is observed."],
  ["subrayar", "to underline / to stress", "soo-bra-YAR", "verb", null, "verbs", "Subrayó la urgencia del asunto.", "He stressed the urgency of the matter."],
  ["la salvedad", "caveat", "la sal-be-DAD", "noun", "f", "abstract", "Lo acepto, con una salvedad.", "I accept it, with one caveat.", { difficulty: 4 }],
  ["la índole", "nature / kind", "la EEN-do-le", "noun", "f", "abstract", "Son problemas de otra índole.", "They are problems of a different nature."],
  ["el alcance", "scope / reach", "el al-KAN-the", "noun", "m", "abstract", "No medimos el alcance del cambio.", "We did not gauge the scope of the change."],
  ["la pauta", "guideline / pattern", "la PAW-ta", "noun", "f", "abstract", "El informe marca las pautas.", "The report sets the guidelines."],
  ["el criterio", "criterion / judgement", "el kree-TE-ryo", "noun", "m", "abstract", "Actuó con buen criterio.", "She used good judgement."],
  ["el desenlace", "outcome / ending", "el de-sen-LA-the", "noun", "m", "abstract", "El desenlace sorprendió a la crítica.", "The ending surprised the critics."],

  // ─── Society & institutions ───────────────────────────────────────────────
  ["la desigualdad", "inequality", "la de-see-gwal-DAD", "noun", "f", "society", "La desigualdad se ha agravado.", "Inequality has worsened."],
  ["la convivencia", "coexistence / living together", "la kon-bee-BEN-thya", "noun", "f", "society", "La convivencia exige acuerdos.", "Coexistence requires agreements."],
  ["el arraigo", "roots / attachment", "el a-RRAY-go", "noun", "m", "society", "Es una tradición de mucho arraigo.", "It is a deeply rooted tradition."],
  ["la ciudadanía activa", "active citizenship", "la thyoo-da-da-NEE-a ak-TEE-ba", "phrase", null, "society", "Promueven la ciudadanía activa.", "They promote active citizenship."],
  ["la cobertura", "coverage", "la ko-ber-TOO-ra", "noun", "f", "media", "La cobertura mediática fue desigual.", "Media coverage was uneven."],
  ["el sesgo mediático", "media bias", "el SES-go me-DYA-tee-ko", "phrase", null, "media", "Denunció el sesgo mediático del canal.", "She called out the channel's media bias."],
  ["acaparar", "to hoard / to monopolise", "a-ka-pa-RAR", "verb", null, "verbs", "Acaparó toda la atención.", "He monopolised all the attention."],
  ["agravarse", "to worsen", "a-gra-BAR-se", "verb", null, "verbs", "La situación se agravó en horas.", "The situation worsened within hours.", { antonyms: ["mejorar"] }],
  ["fraguar", "to hatch / to take shape", "fra-GWAR", "verb", null, "verbs", "El acuerdo se fraguó en secreto.", "The agreement was hatched in secret."],
  ["consolidarse", "to become established", "kon-so-lee-DAR-se", "verb", null, "verbs", "La tendencia se ha consolidado.", "The trend has become established."],
  ["el auge", "boom / peak", "el AW-he", "noun", "m", "economy", "El sector vive un auge inesperado.", "The sector is enjoying an unexpected boom.", { antonyms: ["el declive"] }],
  ["el declive", "decline", "el de-KLEE-be", "noun", "m", "economy", "La industria entró en declive.", "The industry went into decline.", { antonyms: ["el auge"] }],

  // ─── Register & nuance ────────────────────────────────────────────────────
  ["rotundo", "categorical", "rro-TOON-do", "adjective", null, "abstract", "Fue un no rotundo.", "It was a flat no."],
  ["escueto", "terse / concise", "es-KWE-to", "adjective", null, "abstract", "Envió una respuesta escueta.", "He sent a terse reply."],
  ["contundente", "forceful / compelling", "kon-toon-DEN-te", "adjective", null, "abstract", "Presentó pruebas contundentes.", "She presented compelling evidence."],
  ["endeble", "flimsy", "en-DE-ble", "adjective", null, "abstract", "El razonamiento es endeble.", "The reasoning is flimsy."],
  ["ambiguo", "ambiguous", "am-BEE-gwo", "adjective", null, "abstract", "Dio una respuesta ambigua.", "He gave an ambiguous answer."],
  ["acertado", "apt / well judged", "a-ther-TA-do", "adjective", null, "abstract", "Fue una decisión acertada.", "It was a well-judged decision.", { antonyms: ["desacertado"] }],
  ["deliberado", "deliberate", "de-lee-be-RA-do", "adjective", null, "abstract", "Fue una omisión deliberada.", "It was a deliberate omission."],
  ["susceptible", "liable / touchy", "soos-thep-TEE-ble", "adjective", null, "people", "Es susceptible de mejora.", "It is open to improvement."],
  ["reacio", "reluctant", "rre-A-thyo", "adjective", null, "people", "Se muestra reacio a firmar.", "He is reluctant to sign."],
  ["propenso", "prone", "pro-PEN-so", "adjective", null, "people", "Es propenso a exagerar.", "He is prone to exaggerate."],

  // ─── Connectors for formal writing ────────────────────────────────────────
  ["por ende", "hence", "por EN-de", "phrase", null, "connectors", "Faltan datos y, por ende, conclusiones.", "Data is missing and hence so are conclusions.", { difficulty: 4 }],
  ["en la medida en que", "insofar as", "en la me-DEE-da en ke", "phrase", null, "connectors", "Ayuda en la medida en que reduce costes.", "It helps insofar as it reduces costs."],
  ["habida cuenta de", "given / in view of", "a-BEE-da KWEN-ta de", "phrase", null, "connectors", "Habida cuenta de los hechos, dimitió.", "In view of the facts, he resigned."],
  ["a tenor de", "in line with", "a te-NOR de", "phrase", null, "connectors", "A tenor de lo expuesto, procede revisarlo.", "In line with the above, it should be reviewed."],
  ["por lo que respecta a", "as regards", "por lo ke rres-PEK-ta a", "phrase", null, "connectors", "Por lo que respecta al plazo, no hay cambios.", "As regards the deadline, there are no changes."],
  ["si bien", "although (formal)", "see byen", "phrase", null, "connectors", "Si bien es cierto, conviene matizarlo.", "While that is true, it needs qualifying."],
  ["a sabiendas de", "knowingly", "a sa-BYEN-das de", "phrase", null, "connectors", "Firmó a sabiendas del riesgo.", "He signed knowing the risk."],
  ["dado que", "given that", "DA-do ke", "phrase", null, "connectors", "Dado que no hay quórum, se aplaza.", "Given that there is no quorum, it is postponed."],
  ["con vistas a", "with a view to", "kon BEES-tas a", "phrase", null, "connectors", "Se reunieron con vistas a un pacto.", "They met with a view to a deal."],
  ["en detrimento de", "to the detriment of", "en de-tree-MEN-to de", "phrase", null, "connectors", "Creció en detrimento de la calidad.", "It grew to the detriment of quality."],

  // ─── Idiom & colloquial fluency ───────────────────────────────────────────
  ["dar en el clavo", "to hit the nail on the head", "dar en el KLA-bo", "phrase", null, "expressions", "Diste en el clavo con esa idea.", "You hit the nail on the head with that idea."],
  ["ir al grano", "to get to the point", "eer al GRA-no", "phrase", null, "expressions", "Vamos al grano, que no hay tiempo.", "Let us get to the point, there is no time."],
  ["estar en el aire", "to be up in the air", "es-TAR en el AY-re", "phrase", null, "expressions", "El proyecto sigue en el aire.", "The project is still up in the air."],
  ["tirar la toalla", "to throw in the towel", "tee-RAR la to-A-ya", "phrase", null, "expressions", "No tires la toalla ahora.", "Do not throw in the towel now."],
  ["poner el dedo en la llaga", "to touch a nerve", "po-NER el DE-do en la YA-ga", "phrase", null, "expressions", "Puso el dedo en la llaga.", "She touched a nerve."],
  ["a duras penas", "barely", "a DOO-ras PE-nas", "phrase", null, "expressions", "A duras penas llegamos a fin de mes.", "We barely make it to the end of the month."],
  ["de buenas a primeras", "out of the blue", "de BWE-nas a pree-ME-ras", "phrase", null, "expressions", "De buenas a primeras, dimitió.", "Out of the blue, he resigned."],
  ["no tener desperdicio", "to be well worth it throughout", "no te-NER des-per-DEE-thyo", "phrase", null, "expressions", "La entrevista no tiene desperdicio.", "Every bit of the interview is worth hearing."],
  ["por si fuera poco", "as if that were not enough", "por see FWE-ra PO-ko", "phrase", null, "expressions", "Y por si fuera poco, llovía.", "And as if that were not enough, it was raining."],
  ["dejar mucho que desear", "to leave much to be desired", "de-HAR MOO-cho ke de-se-AR", "phrase", null, "expressions", "El servicio deja mucho que desear.", "The service leaves much to be desired."],
  ["desacertado", "misguided", "de-sa-ther-TA-do", "adjective", null, "abstract", "Fue un comentario desacertado.", "It was a misguided remark."],
];
