import type { Row } from "./row.js";

export const C1_ROWS: Row[] = [
  ["el acervo", "heritage / body (of work)", "el a-THER-bo", "noun", "m", "academic", "Forma parte del acervo cultural del país.", "It is part of the country's cultural heritage."],
  ["soslayar", "to sidestep / avoid", "sos-la-YAR", "verb", null, "academic", "El informe soslaya el problema de fondo.", "The report sidesteps the underlying problem."],
  ["subyacente", "underlying", "soob-ya-THEN-te", "adjective", null, "academic", "La causa subyacente es económica.", "The underlying cause is economic."],
  ["esgrimir", "to wield (an argument)", "es-gree-MEER", "verb", null, "debate", "Esgrimió datos poco fiables.", "He wielded unreliable data."],
  ["el desdén", "disdain", "el des-DEN", "noun", "m", "literature", "Lo dijo con cierto desdén.", "He said it with a certain disdain."],
  ["huelga decir", "needless to say", "WEL-ga de-THEER", "phrase", null, "expressions", "Huelga decir que no asistió.", "Needless to say, he didn't attend."],
  ["a todas luces", "clearly / by any measure", "a TO-das LOO-thes", "phrase", null, "expressions", "Es a todas luces insuficiente.", "It is clearly insufficient."],
  ["en aras de", "for the sake of", "en A-ras de", "phrase", null, "academic", "En aras de la transparencia, publicamos todo.", "For the sake of transparency, we publish everything."],
  ["paliar", "to alleviate", "pa-LYAR", "verb", null, "academic", "Las ayudas palian el impacto.", "The subsidies alleviate the impact."],
  ["el revuelo", "stir / commotion", "el re-BWE-lo", "noun", "m", "journalism", "Sus declaraciones causaron revuelo.", "His statements caused a stir."],
  // ─── Precision verbs ──────────────────────────────────────────────────────
  ["dilucidar", "to elucidate", "dee-loo-thee-DAR", "verb", null, "verbs", "Falta dilucidar quién dio la orden.", "It remains to be clarified who gave the order."],
  ["socavar", "to undermine", "so-ka-BAR", "verb", null, "verbs", "El escándalo socavó su autoridad.", "The scandal undermined his authority."],
  ["entrañar", "to entail", "en-tra-NYAR", "verb", null, "verbs", "La medida entraña riesgos evidentes.", "The measure entails obvious risks."],
  ["propiciar", "to bring about / to favour", "pro-pee-THYAR", "verb", null, "verbs", "El acuerdo propició la reforma.", "The agreement paved the way for the reform."],
  ["vislumbrar", "to glimpse / to make out", "bees-loom-BRAR", "verb", null, "verbs", "Se vislumbra una salida.", "A way out is beginning to appear."],
  ["ceñirse a", "to stick to", "the-NYEER-se a", "verb", null, "verbs", "Cíñete a los hechos.", "Stick to the facts."],
  ["supeditar", "to subordinate", "soo-pe-dee-TAR", "verb", null, "verbs", "Supeditó todo al resultado.", "He subordinated everything to the outcome."],
  ["zanjar", "to settle (a matter)", "than-HAR", "verb", null, "verbs", "Zanjaron la polémica en una tarde.", "They settled the controversy in an afternoon."],
  ["esbozar", "to outline / to sketch", "es-bo-THAR", "verb", null, "verbs", "Esbozó una sonrisa.", "He gave a faint smile."],
  ["encauzar", "to channel / to steer", "en-kaw-THAR", "verb", null, "verbs", "Hay que encauzar el debate.", "The debate needs steering back on track."],
  ["desvirtuar", "to distort", "des-beer-TWAR", "verb", null, "verbs", "El titular desvirtúa el estudio.", "The headline distorts the study."],
  ["granjearse", "to earn (respect, enmity)", "gran-he-AR-se", "verb", null, "verbs", "Se granjeó el respeto de todos.", "He earned everyone's respect."],
  ["allanar", "to smooth / to raid", "a-ya-NAR", "verb", null, "verbs", "Su gestión allanó el camino.", "Her handling of it smoothed the way."],
  ["recabar", "to gather (information)", "rre-ka-BAR", "verb", null, "verbs", "Recabaron datos durante meses.", "They gathered data for months."],
  ["atañer", "to concern", "a-ta-NYER", "verb", null, "verbs", "En lo que atañe al presupuesto, no hay acuerdo.", "As far as the budget is concerned, there is no agreement."],

  // ─── Abstract & literary nouns ────────────────────────────────────────────
  ["el atisbo", "hint / glimmer", "el a-TEES-bo", "noun", "m", "abstract", "No hay ni un atisbo de duda.", "There is not a shred of doubt."],
  ["el hincapié", "emphasis", "el een-ka-PYE", "noun", "m", "abstract", "Hizo hincapié en la prevención.", "She placed emphasis on prevention."],
  ["el cariz", "look / turn (of events)", "el ka-REETH", "noun", "m", "abstract", "El asunto tomó mal cariz.", "The matter took a bad turn."],
  ["el ocaso", "twilight / decline", "el o-KA-so", "noun", "m", "abstract", "Vivimos el ocaso de un modelo.", "We are witnessing the twilight of a model."],
  ["la merma", "reduction / loss", "la MER-ma", "noun", "f", "abstract", "Hubo una merma notable de ingresos.", "There was a notable drop in income."],
  ["el arrebato", "outburst", "el a-rre-BA-to", "noun", "m", "feelings", "Lo dijo en un arrebato de ira.", "He said it in a fit of rage."],
  ["la añoranza", "longing / nostalgia", "la a-nyo-RAN-tha", "noun", "f", "feelings", "Habla de su pueblo con añoranza.", "He speaks of his village with longing."],
  ["el desasosiego", "unease", "el de-sa-so-SYE-go", "noun", "m", "feelings", "La noticia causó desasosiego.", "The news caused unease."],
  ["la ecuanimidad", "even-handedness", "la e-kwa-nee-mee-DAD", "noun", "f", "abstract", "Juzgó el caso con ecuanimidad.", "She judged the case even-handedly."],
  ["el trasfondo", "underlying background", "el tras-FON-do", "noun", "m", "abstract", "El trasfondo del conflicto es económico.", "The underlying context of the conflict is economic."],
  ["la injerencia", "interference", "la een-he-REN-thya", "noun", "f", "politics", "Denunció la injerencia extranjera.", "He denounced foreign interference."],
  ["el menoscabo", "damage / impairment", "el me-nos-KA-bo", "noun", "m", "abstract", "Sin menoscabo de su derecho a recurrir.", "Without prejudice to their right of appeal.", { difficulty: 5 }],

  // ─── Refined adjectives ───────────────────────────────────────────────────
  ["consabido", "well-known / the usual", "kon-sa-BEE-do", "adjective", null, "abstract", "Llegó con la consabida excusa.", "He arrived with the usual excuse."],
  ["soslayable", "avoidable", "sos-la-YA-ble", "adjective", null, "abstract", "El conflicto era perfectamente soslayable.", "The conflict was entirely avoidable."],
  ["acuciante", "pressing", "a-koo-THYAN-te", "adjective", null, "abstract", "Es una necesidad acuciante.", "It is a pressing need."],
  ["baladí", "trivial", "ba-la-DEE", "adjective", null, "abstract", "No es un detalle baladí.", "It is not a trivial detail."],
  ["paulatino", "gradual", "paw-la-TEE-no", "adjective", null, "abstract", "Se observa un descenso paulatino.", "A gradual decline is observed."],
  ["taxativo", "categorical / strict", "tak-sa-TEE-bo", "adjective", null, "abstract", "La norma es taxativa.", "The rule is categorical."],
  ["encomiable", "commendable", "en-ko-MYA-ble", "adjective", null, "abstract", "Realizó una labor encomiable.", "She did commendable work."],
  ["aciago", "fateful / ill-fated", "a-THYA-go", "adjective", null, "abstract", "Aquel fue un día aciago.", "That was a fateful day."],
  ["prolijo", "long-winded / meticulous", "pro-LEE-ho", "adjective", null, "abstract", "El informe es prolijo en detalles.", "The report is exhaustive in its detail."],
  ["ineludible", "unavoidable", "ee-ne-loo-DEE-ble", "adjective", null, "abstract", "Es un compromiso ineludible.", "It is an unavoidable commitment."],

  // ─── Formal discourse ─────────────────────────────────────────────────────
  ["por cuanto", "inasmuch as", "por KWAN-to", "phrase", null, "connectors", "Se desestima por cuanto carece de fundamento.", "It is dismissed inasmuch as it lacks grounds."],
  ["sin perjuicio de", "without prejudice to", "seen per-HWEE-thyo de", "phrase", null, "connectors", "Sin perjuicio de lo anterior, cabe recurso.", "Without prejudice to the above, an appeal is possible."],
  ["a fuer de", "as befits / by dint of", "a fwer de", "phrase", null, "connectors", "A fuer de sincero, no me convenció.", "To be honest, it did not convince me.", { difficulty: 5 }],
  ["en aras a la claridad", "for the sake of clarity", "en A-ras a la kla-ree-DAD", "phrase", null, "connectors", "En aras a la claridad, lo resumo.", "For the sake of clarity, I will summarise it."],
  ["dicho sea de paso", "incidentally", "DEE-cho SE-a de PA-so", "phrase", null, "connectors", "Dicho sea de paso, nadie protestó.", "Incidentally, nobody protested."],
  ["ni mucho menos", "far from it", "nee MOO-cho ME-nos", "phrase", null, "expressions", "No es lo peor, ni mucho menos.", "It is not the worst, far from it."],
  ["a decir verdad", "truth be told", "a de-THEER ber-DAD", "phrase", null, "expressions", "A decir verdad, me sorprendió.", "Truth be told, it surprised me."],
  ["por más que", "however much", "por mas ke", "phrase", null, "connectors", "Por más que insista, no cederá.", "However much he insists, she will not give in."],
  ["a expensas de", "at the expense of", "a eks-PEN-sas de", "phrase", null, "connectors", "Creció a expensas de sus rivales.", "It grew at the expense of its rivals."],
];
